<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 10 Introduction to one way ANOVA | Quantitative and spatial analysis</title>
  <meta name="description" content="Chapter 10 Introduction to one way ANOVA | Quantitative and spatial analysis">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 10 Introduction to one way ANOVA | Quantitative and spatial analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Introduction to one way ANOVA | Quantitative and spatial analysis" />
  
  
  

<meta name="author" content="Duncan Golicher">


<meta name="date" content="2019-12-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="t-tests-and-hypothesis-testing.html">
<link rel="next" href="regression-as-a-statistical-modelling.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<script src="libs/jszip-1.10.16/jszip.min.js"></script>
<link href="libs/dt-ext-buttons-1.10.16/css/buttons.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-buttons-1.10.16/js/dataTables.buttons.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.flash.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.html5.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.colVis.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.print.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<link href="libs/PopupTable-0.0.1/popup.css" rel="stylesheet" />
<link href="libs/lfx-fullscreen-1.0.2/lfx-fullscreen-prod.css" rel="stylesheet" />
<script src="libs/lfx-fullscreen-1.0.2/lfx-fullscreen-prod.js"></script>
<link href="libs/leaflet-minimap-3.3.1/Control.MiniMap.min.css" rel="stylesheet" />
<script src="libs/leaflet-minimap-3.3.1/Control.MiniMap.min.js"></script>
<script src="libs/leaflet-minimap-3.3.1/Minimap-binding.js"></script>
<link href="libs/lfx-measure-path-1.3.1/lfx-measure-path-prod.css" rel="stylesheet" />
<script src="libs/lfx-measure-path-1.3.1/lfx-measure-path-prod.js"></script>
<script src="libs/lfx-measure-path-1.3.1/lfx-measure-path-bindings.js"></script>
<link href="libs/leaflet-easybutton-1.3.1/easy-button.css" rel="stylesheet" />
<script src="libs/leaflet-easybutton-1.3.1/easy-button.js"></script>
<script src="libs/leaflet-easybutton-1.3.1/EasyButton-binding.js"></script>
<link href="libs/ionicons-2.0.1/ionicons.min.css" rel="stylesheet" />
<link href="libs/leaflet-measure-2.1.7/leaflet-measure.css" rel="stylesheet" />
<script src="libs/leaflet-measure-2.1.7/leaflet-measure.min.js"></script>
<script src="libs/aspect-1/data_stars_aspecte26b50.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/dtm-1/data_stars_dtm1cb720.txt"></script>
<script src="libs/fuse_js-3.2.0/fuse_js-prod.js"></script>
<link href="libs/lfx-search-2.3.7/lfx-search-prod.css" rel="stylesheet" />
<script src="libs/lfx-search-2.3.7/lfx-search-prod.js"></script>
<script src="libs/lfx-search-2.3.7/lfx-search-bindings.js"></script>
<script src="libs/dsm-1/data_stars_dsm4d7328.txt"></script>
<script src="libs/chm10-1/data_stars_chm1086d415.txt"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative and spatial</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html"><i class="fa fa-check"></i><b>1</b> Introduction to GIS</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#what-is-a-gis"><i class="fa fa-check"></i><b>1.1</b> What is a GIS?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#desktop-gis"><i class="fa fa-check"></i><b>1.2</b> Desktop GIS</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#some-key-gis-concept"><i class="fa fa-check"></i><b>1.3</b> Some key GIS concept</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#coordinate-reference-systems-and-projections."><i class="fa fa-check"></i><b>1.3.1</b> Coordinate reference systems and projections.</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#raster-vs-vector-data"><i class="fa fa-check"></i><b>1.3.2</b> Raster vs vector data</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#making-your-own-maps"><i class="fa fa-check"></i><b>1.4</b> Making your own maps</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#the-qgis-interface"><i class="fa fa-check"></i><b>1.4.1</b> The QGIS interface</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#qgis-gui"><i class="fa fa-check"></i><b>1.4.2</b> QGIS GUI</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#adding-base-maps"><i class="fa fa-check"></i><b>1.4.3</b> Adding base maps</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#loading-a-base-map"><i class="fa fa-check"></i><b>1.4.4</b> Loading a base map</a></li>
<li class="chapter" data-level="1.4.5" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#saving-projects-and-files"><i class="fa fa-check"></i><b>1.4.5</b> Saving projects and files</a></li>
<li class="chapter" data-level="1.4.6" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#adding-a-wcs-raster-layer-from-the-local-geoserver"><i class="fa fa-check"></i><b>1.4.6</b> Adding a WCS raster layer from the local Geoserver</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#raster-terrain-data"><i class="fa fa-check"></i><b>1.5</b> Raster terrain data</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#vector-data-from-the-wfs-service"><i class="fa fa-check"></i><b>1.6</b> Vector data from the WFS service</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#saving-layers-locally-for-processing-and-offline-use"><i class="fa fa-check"></i><b>1.7</b> Saving layers locally for processing and offline use</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html"><i class="fa fa-check"></i><b>2</b> On screen digitising</a><ul>
<li class="chapter" data-level="2.1" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#digitising-tool-bar"><i class="fa fa-check"></i><b>2.1</b> Digitising tool bar</a></li>
<li class="chapter" data-level="2.2" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#drawing-a-polygon"><i class="fa fa-check"></i><b>2.2</b> Drawing a polygon</a><ul>
<li class="chapter" data-level="2.2.1" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#valid-and-invalid-geometries"><i class="fa fa-check"></i><b>2.2.1</b> Valid and invalid geometries</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#saving-the-polygon"><i class="fa fa-check"></i><b>2.3</b> Saving the polygon</a></li>
<li class="chapter" data-level="2.4" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#snapping"><i class="fa fa-check"></i><b>2.4</b> Snapping</a></li>
<li class="chapter" data-level="2.5" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#avoiding-intersections"><i class="fa fa-check"></i><b>2.5</b> Avoiding intersections</a></li>
<li class="chapter" data-level="2.6" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#splitting-on-paths"><i class="fa fa-check"></i><b>2.6</b> Splitting on paths</a></li>
<li class="chapter" data-level="2.7" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#summary"><i class="fa fa-check"></i><b>2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html"><i class="fa fa-check"></i><b>3</b> Styling and cartography</a><ul>
<li class="chapter" data-level="3.1" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#using-a-prebuilt-style"><i class="fa fa-check"></i><b>3.2</b> Using a prebuilt style</a><ul>
<li class="chapter" data-level="3.2.1" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#finding-the-styling-dialogue"><i class="fa fa-check"></i><b>3.2.1</b> Finding the styling dialogue</a></li>
<li class="chapter" data-level="3.2.2" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#loading-the-style-sheet-colour-scheme-for-the-polygons."><i class="fa fa-check"></i><b>3.2.2</b> Loading the style sheet colour scheme for the polygons.</a></li>
<li class="chapter" data-level="3.2.3" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#filtering-the-visible-styles"><i class="fa fa-check"></i><b>3.2.3</b> Filtering the visible styles</a></li>
<li class="chapter" data-level="3.2.4" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#copying-and-pasting-styles"><i class="fa fa-check"></i><b>3.2.4</b> Copying and pasting styles</a></li>
<li class="chapter" data-level="3.2.5" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#adding-derived-attributes"><i class="fa fa-check"></i><b>3.2.5</b> Adding derived attributes</a></li>
<li class="chapter" data-level="3.2.6" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#cartography-designing-a-prinatable-map"><i class="fa fa-check"></i><b>3.2.6</b> Cartography: Designing a prinatable map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="terrain-analysis.html"><a href="terrain-analysis.html"><i class="fa fa-check"></i><b>4</b> Terrain analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#what-is-terrain-analysis"><i class="fa fa-check"></i><b>4.1</b> What is terrain analysis</a></li>
<li class="chapter" data-level="4.2" data-path="terrain-analysis.html"><a href="terrain-analysis.html#lidar-data"><i class="fa fa-check"></i><b>4.2</b> Lidar data</a></li>
<li class="chapter" data-level="4.3" data-path="terrain-analysis.html"><a href="terrain-analysis.html#working-with-lidar-data-in-qgis"><i class="fa fa-check"></i><b>4.3</b> Working with Lidar data in QGIS</a><ul>
<li class="chapter" data-level="4.3.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#analytical-hill-shading"><i class="fa fa-check"></i><b>4.3.1</b> Analytical hill shading</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="terrain-analysis.html"><a href="terrain-analysis.html#colouring-the-dtm"><i class="fa fa-check"></i><b>4.4</b> Colouring the DTM</a><ul>
<li class="chapter" data-level="4.4.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#adding-contour-lines"><i class="fa fa-check"></i><b>4.4.1</b> Adding contour lines</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-slope-and-aspect"><i class="fa fa-check"></i><b>4.5</b> Calculating slope and aspect</a><ul>
<li class="chapter" data-level="4.5.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#slope"><i class="fa fa-check"></i><b>4.5.1</b> Slope</a></li>
<li class="chapter" data-level="4.5.2" data-path="terrain-analysis.html"><a href="terrain-analysis.html#aspect"><i class="fa fa-check"></i><b>4.5.2</b> Aspect</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-canopy-height."><i class="fa fa-check"></i><b>4.6</b> Calculating canopy height.</a></li>
<li class="chapter" data-level="4.7" data-path="terrain-analysis.html"><a href="terrain-analysis.html#investigating-canopy-height-in-3d"><i class="fa fa-check"></i><b>4.7</b> Investigating canopy height in 3D</a></li>
<li class="chapter" data-level="4.8" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-raster-stats-for-polygons."><i class="fa fa-check"></i><b>4.8</b> Calculating raster stats for polygons.</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html"><i class="fa fa-check"></i><b>5</b> Introduction to the RStudio Server</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#getting-started-with-the-rstudio-server"><i class="fa fa-check"></i><b>5.2</b> Getting started with the RStudio server</a><ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-log-into-the-rstudio-server"><i class="fa fa-check"></i><b>5.2.1</b> Action: Log into the RStudio server</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#rstudio-server-concepts"><i class="fa fa-check"></i><b>5.3</b> RStudio server concepts</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#finding-your-way-around-the-interface"><i class="fa fa-check"></i><b>5.4</b> Finding your way around the interface</a><ul>
<li class="chapter" data-level="5.4.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#using-projects-in-rstudio"><i class="fa fa-check"></i><b>5.4.1</b> Using projects in RStudio</a></li>
<li class="chapter" data-level="5.4.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-form-a-new-project-and-add-a-new-folder"><i class="fa fa-check"></i><b>5.4.2</b> Action: Form a new project and add a new folder</a></li>
<li class="chapter" data-level="5.4.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#using-the-console"><i class="fa fa-check"></i><b>5.4.3</b> Using the console</a></li>
<li class="chapter" data-level="5.4.4" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-make-a-data-object-vector-in-r"><i class="fa fa-check"></i><b>5.4.4</b> Action: Make a data object (vector) in R</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#data-abstraction-and-data-visualisation"><i class="fa fa-check"></i><b>5.5</b> Data abstraction and data visualisation</a><ul>
<li class="chapter" data-level="5.5.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-visualise-the-data-using-a-simple-histogram"><i class="fa fa-check"></i><b>5.5.1</b> Action: Visualise the data using a simple histogram</a></li>
<li class="chapter" data-level="5.5.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-close-the-project"><i class="fa fa-check"></i><b>5.5.2</b> Action: Close the project</a></li>
<li class="chapter" data-level="5.5.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-restore-the-project"><i class="fa fa-check"></i><b>5.5.3</b> Action: Restore the project</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#working-with-markdown-documents."><i class="fa fa-check"></i><b>5.6</b> Working with markdown documents.</a><ul>
<li class="chapter" data-level="5.6.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-produce-a-default-markdown-document."><i class="fa fa-check"></i><b>5.6.1</b> Action: Produce a default markdown document.</a></li>
<li class="chapter" data-level="5.6.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-clean-out-rinse-and-repeat-for-practice-sake"><i class="fa fa-check"></i><b>5.6.2</b> Action: Clean out, rinse and repeat, for practice sake</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#conclusion"><i class="fa fa-check"></i><b>5.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html"><i class="fa fa-check"></i><b>6</b> Basic statistical concepts. Refresher using a simple example</a><ul>
<li class="chapter" data-level="6.0.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#getting-some-data"><i class="fa fa-check"></i><b>6.0.1</b> Getting some data</a></li>
<li class="chapter" data-level="6.0.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-get-some-personal-data"><i class="fa fa-check"></i><b>6.0.2</b> Action: Get some personal data</a></li>
<li class="chapter" data-level="6.0.3" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-summarise-the-class-data"><i class="fa fa-check"></i><b>6.0.3</b> Action: Summarise the class data</a></li>
<li class="chapter" data-level="6.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#inferential-statistics"><i class="fa fa-check"></i><b>6.1</b> Inferential statistics</a><ul>
<li class="chapter" data-level="6.1.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-calculate-the-standard-deviation-by-hand"><i class="fa fa-check"></i><b>6.1.1</b> Action: Calculate the standard deviation “by hand”</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#calcuate-the-standard-error-of-the-mean."><i class="fa fa-check"></i><b>6.2</b> Calcuate the standard error of the mean.</a><ul>
<li class="chapter" data-level="6.2.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-calculate-the-standard-error-and-95-confidence-interval-for-the-mean"><i class="fa fa-check"></i><b>6.2.1</b> Action: Calculate the standard error and 95% confidence interval for the mean</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#test-whether-the-statistics-work"><i class="fa fa-check"></i><b>6.3</b> Test whether the statistics “work”</a><ul>
<li class="chapter" data-level="6.3.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-rinse-and-repeat."><i class="fa fa-check"></i><b>6.3.1</b> Action: Rinse and repeat.</a></li>
<li class="chapter" data-level="6.3.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#conclusion-1"><i class="fa fa-check"></i><b>6.3.2</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#planning-an-analysis"><i class="fa fa-check"></i><b>6.4</b> Planning an analysis</a><ul>
<li class="chapter" data-level="6.4.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#understanding-your-data-before-you-start-colllecting-them"><i class="fa fa-check"></i><b>6.4.1</b> Understanding your data before you start colllecting them</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#quantitative-analysis"><i class="fa fa-check"></i><b>6.5</b> Quantitative analysis</a></li>
<li class="chapter" data-level="6.6" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#what-does-quantitative-data-consist-of"><i class="fa fa-check"></i><b>6.6</b> What does quantitative data consist of?</a></li>
<li class="chapter" data-level="6.7" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#data-visualisation-vs-statistical-analysis"><i class="fa fa-check"></i><b>6.7</b> Data visualisation vs statistical analysis</a></li>
<li class="chapter" data-level="6.8" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#a-simple-example"><i class="fa fa-check"></i><b>6.8</b> A simple example</a></li>
<li class="chapter" data-level="6.9" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#graphical-data-analysis"><i class="fa fa-check"></i><b>6.9</b> Graphical data analysis</a></li>
<li class="chapter" data-level="6.10" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#forming-a-plot-in-r"><i class="fa fa-check"></i><b>6.10</b> Forming a plot in R</a></li>
<li class="chapter" data-level="6.11" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#a-more-complex-time-series"><i class="fa fa-check"></i><b>6.11</b> A more complex time series</a></li>
<li class="chapter" data-level="6.12" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#some-high-level-code-to-break-down-the-data"><i class="fa fa-check"></i><b>6.12</b> Some high level code to break down the data</a></li>
<li class="chapter" data-level="6.13" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#inferential-statistics-1"><i class="fa fa-check"></i><b>6.13</b> Inferential statistics</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html"><i class="fa fa-check"></i><b>7</b> Confidence intervals for univariate data</a><ul>
<li class="chapter" data-level="7.1" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#introduction-2"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#reminder-basic-statistics"><i class="fa fa-check"></i><b>7.2</b> Reminder: Basic statistics</a></li>
<li class="chapter" data-level="7.3" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.3</b> Measures of central tendency</a><ul>
<li class="chapter" data-level="7.3.1" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#measures-of-variability"><i class="fa fa-check"></i><b>7.3.1</b> Measures of variability</a></li>
<li class="chapter" data-level="7.3.2" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#the-normal-distribution"><i class="fa fa-check"></i><b>7.3.2</b> The normal distribution</a></li>
<li class="chapter" data-level="7.3.3" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#checking-data-properties-with-figures"><i class="fa fa-check"></i><b>7.3.3</b> Checking data properties with figures</a></li>
<li class="chapter" data-level="7.3.4" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#calculating-the-standard-error"><i class="fa fa-check"></i><b>7.3.4</b> Calculating the standard error</a></li>
<li class="chapter" data-level="7.3.5" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#the-sampling-distribution-of-the-mean"><i class="fa fa-check"></i><b>7.3.5</b> The sampling distribution of the mean</a></li>
<li class="chapter" data-level="7.3.6" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#calculating-confidence-intervals"><i class="fa fa-check"></i><b>7.3.6</b> Calculating confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#conclusion-and-take-home-messages"><i class="fa fa-check"></i><b>7.4</b> Conclusion and take home messages</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html"><i class="fa fa-check"></i><b>8</b> Using figures to understand and present data</a><ul>
<li class="chapter" data-level="8.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#quick-exploratory-plots"><i class="fa fa-check"></i><b>8.1</b> Quick exploratory plots</a></li>
<li class="chapter" data-level="8.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#introduction-to-grammar-of-graphics-plots"><i class="fa fa-check"></i><b>8.2</b> Introduction to grammar of graphics plots</a></li>
<li class="chapter" data-level="8.3" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#simple-bar-charts"><i class="fa fa-check"></i><b>8.3</b> Simple bar charts</a><ul>
<li class="chapter" data-level="8.3.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#exercise-3"><i class="fa fa-check"></i><b>8.3.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#simple-line-charts"><i class="fa fa-check"></i><b>8.4</b> Simple Line charts</a><ul>
<li class="chapter" data-level="8.4.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#exercise-4"><i class="fa fa-check"></i><b>8.4.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#histograms"><i class="fa fa-check"></i><b>8.5</b> Histograms</a><ul>
<li class="chapter" data-level="8.5.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#default-histogram"><i class="fa fa-check"></i><b>8.5.1</b> Default histogram</a></li>
<li class="chapter" data-level="8.5.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#facet-wrapping"><i class="fa fa-check"></i><b>8.5.2</b> Facet wrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#boxplots"><i class="fa fa-check"></i><b>8.6</b> Boxplots</a></li>
<li class="chapter" data-level="8.7" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#confidence-interval-plots"><i class="fa fa-check"></i><b>8.7</b> Confidence interval plots</a><ul>
<li class="chapter" data-level="8.7.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#dynamite-plots-dont-use"><i class="fa fa-check"></i><b>8.7.1</b> Dynamite plots (Don’t use!)</a></li>
<li class="chapter" data-level="8.7.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#inference-on-medians"><i class="fa fa-check"></i><b>8.7.2</b> Inference on medians</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#scatterplots"><i class="fa fa-check"></i><b>8.8</b> Scatterplots</a><ul>
<li class="chapter" data-level="8.8.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#adding-a-regression-line"><i class="fa fa-check"></i><b>8.8.1</b> Adding a regression line</a></li>
<li class="chapter" data-level="8.8.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#grouping-and-conditioning"><i class="fa fa-check"></i><b>8.8.2</b> Grouping and conditioning</a></li>
<li class="chapter" data-level="8.8.3" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#curvilinear-relationships"><i class="fa fa-check"></i><b>8.8.3</b> Curvilinear relationships</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#generalised-linear-models"><i class="fa fa-check"></i><b>8.9</b> Generalised linear models</a></li>
<li class="chapter" data-level="8.10" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#binomial-data"><i class="fa fa-check"></i><b>8.10</b> Binomial data</a></li>
<li class="chapter" data-level="8.11" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#learning-more-about-ggplots"><i class="fa fa-check"></i><b>8.11</b> Learning more about ggplots</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html"><i class="fa fa-check"></i><b>9</b> T tests and hypothesis testing</a><ul>
<li class="chapter" data-level="9.1" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#statistical-hypothesis-testing"><i class="fa fa-check"></i><b>9.1</b> Statistical hypothesis testing</a><ul>
<li class="chapter" data-level="9.1.1" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#the-unpaired-t-test"><i class="fa fa-check"></i><b>9.1.1</b> The unpaired t-test</a></li>
<li class="chapter" data-level="9.1.2" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#the-t-statistic"><i class="fa fa-check"></i><b>9.1.2</b> The t-statistic</a></li>
<li class="chapter" data-level="9.1.3" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#interpretation-of-a-p-value"><i class="fa fa-check"></i><b>9.1.3</b> Interpretation of a p-value</a></li>
<li class="chapter" data-level="9.1.4" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#tests-and-confidence-intervals"><i class="fa fa-check"></i><b>9.1.4</b> Tests and confidence intervals</a></li>
<li class="chapter" data-level="9.1.5" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#using-hypothesis-tests-wisely"><i class="fa fa-check"></i><b>9.1.5</b> Using hypothesis tests wisely</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html"><i class="fa fa-check"></i><b>10</b> Introduction to one way ANOVA</a><ul>
<li class="chapter" data-level="10.0.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#multiple-comparisons"><i class="fa fa-check"></i><b>10.0.1</b> Multiple comparisons</a></li>
<li class="chapter" data-level="10.0.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#visualising-between-group-variation-using-boxplots"><i class="fa fa-check"></i><b>10.0.2</b> Visualising between group variation using boxplots</a></li>
<li class="chapter" data-level="10.0.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#boxplot-statistics"><i class="fa fa-check"></i><b>10.0.3</b> Boxplot statistics</a></li>
<li class="chapter" data-level="10.0.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#plotting-confidence-intervals-for-each-group"><i class="fa fa-check"></i><b>10.0.4</b> Plotting confidence intervals for each group</a></li>
<li class="chapter" data-level="10.0.5" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#fitting-a-model"><i class="fa fa-check"></i><b>10.0.5</b> Fitting a model</a></li>
<li class="chapter" data-level="10.0.6" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#the-f-ratio-and-degrees-of-freedom"><i class="fa fa-check"></i><b>10.0.6</b> The F ratio and degrees of freedom</a></li>
<li class="chapter" data-level="10.0.7" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>10.0.7</b> Homogeneity of variance</a></li>
<li class="chapter" data-level="10.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#alternative-to-the-one-way-test"><i class="fa fa-check"></i><b>10.1</b> Alternative to the one way test</a><ul>
<li class="chapter" data-level="10.1.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#determining-where-the-differences-lie"><i class="fa fa-check"></i><b>10.1.1</b> Determining where the differences lie</a></li>
<li class="chapter" data-level="10.1.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#bonferoni-corrections"><i class="fa fa-check"></i><b>10.1.2</b> Bonferoni corrections</a></li>
<li class="chapter" data-level="10.1.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#tukeys-honest-significant-difference"><i class="fa fa-check"></i><b>10.1.3</b> Tukey’s honest significant difference</a></li>
<li class="chapter" data-level="10.1.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#the-kruskal-wallace-non-parametric-test."><i class="fa fa-check"></i><b>10.1.4</b> The Kruskal Wallace non parametric test.</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#power-analysis"><i class="fa fa-check"></i><b>10.2</b> Power analysis</a></li>
<li class="chapter" data-level="10.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#exercise-5"><i class="fa fa-check"></i><b>10.3</b> Exercise</a></li>
<li class="chapter" data-level="10.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#references"><i class="fa fa-check"></i><b>10.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html"><i class="fa fa-check"></i><b>11</b> Regression as a statistical modelling</a><ul>
<li class="chapter" data-level="11.0.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#uses-of-models"><i class="fa fa-check"></i><b>11.0.1</b> Uses of models</a></li>
<li class="chapter" data-level="11.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#the-general-linear-model"><i class="fa fa-check"></i><b>11.1</b> The general linear model</a></li>
<li class="chapter" data-level="11.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#regression"><i class="fa fa-check"></i><b>11.2</b> Regression</a><ul>
<li class="chapter" data-level="11.2.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#theory"><i class="fa fa-check"></i><b>11.2.1</b> Theory</a></li>
<li class="chapter" data-level="11.2.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#example"><i class="fa fa-check"></i><b>11.2.2</b> Example</a></li>
<li class="chapter" data-level="11.2.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#confidence-intervals"><i class="fa fa-check"></i><b>11.2.3</b> Confidence intervals</a></li>
<li class="chapter" data-level="11.2.4" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#prediction-1"><i class="fa fa-check"></i><b>11.2.4</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#using-ggplot2-for-confidence-intervals."><i class="fa fa-check"></i><b>11.3</b> Using ggplot2 for confidence intervals.</a><ul>
<li class="chapter" data-level="11.3.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#prediction-intervals"><i class="fa fa-check"></i><b>11.3.1</b> Prediction intervals</a></li>
<li class="chapter" data-level="11.3.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#diagnostics"><i class="fa fa-check"></i><b>11.3.2</b> Diagnostics</a></li>
<li class="chapter" data-level="11.3.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#lack-of-independence"><i class="fa fa-check"></i><b>11.3.3</b> Lack of independence</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#where-do-the-sum-of-squares-come-from"><i class="fa fa-check"></i><b>11.4</b> Where do the sum of squares come from?</a><ul>
<li class="chapter" data-level="11.4.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#regression-1"><i class="fa fa-check"></i><b>11.4.1</b> Regression</a></li>
<li class="chapter" data-level="11.4.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#residuals"><i class="fa fa-check"></i><b>11.4.2</b> Residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#where-does-r-squared-coefficient-of-determination-come-from"><i class="fa fa-check"></i><b>11.5</b> Where does R squared (coefficient of determination) come from?</a><ul>
<li class="chapter" data-level="11.5.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#violations-of-assumptions"><i class="fa fa-check"></i><b>11.5.1</b> Violations of assumptions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="advice-on-regression.html"><a href="advice-on-regression.html"><i class="fa fa-check"></i><b>12</b> Advice on regression</a><ul>
<li class="chapter" data-level="12.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#introduction-3"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="advice-on-regression.html"><a href="advice-on-regression.html#predictive-modelling-calibration"><i class="fa fa-check"></i><b>12.2</b> Predictive modelling: Calibration</a><ul>
<li class="chapter" data-level="12.2.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up"><i class="fa fa-check"></i><b>12.2.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="advice-on-regression.html"><a href="advice-on-regression.html#explanatory-modelling"><i class="fa fa-check"></i><b>12.3</b> Explanatory modelling:</a><ul>
<li class="chapter" data-level="12.3.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-1"><i class="fa fa-check"></i><b>12.3.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="advice-on-regression.html"><a href="advice-on-regression.html#testing-for-a-relationship"><i class="fa fa-check"></i><b>12.4</b> Testing for a relationship</a><ul>
<li class="chapter" data-level="12.4.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-2"><i class="fa fa-check"></i><b>12.4.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="advice-on-regression.html"><a href="advice-on-regression.html#diagnostics-show-assumptions-not-met"><i class="fa fa-check"></i><b>12.5</b> Diagnostics show assumptions not met</a></li>
<li class="chapter" data-level="12.6" data-path="advice-on-regression.html"><a href="advice-on-regression.html#skewed-independent-variable"><i class="fa fa-check"></i><b>12.6</b> Skewed independent variable</a><ul>
<li class="chapter" data-level="12.6.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-3"><i class="fa fa-check"></i><b>12.6.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="advice-on-regression.html"><a href="advice-on-regression.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>12.7</b> Spearman’s rank correlation</a><ul>
<li class="chapter" data-level="12.7.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#taking-ranks"><i class="fa fa-check"></i><b>12.7.1</b> Taking ranks</a></li>
<li class="chapter" data-level="12.7.2" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-4"><i class="fa fa-check"></i><b>12.7.2</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="advice-on-regression.html"><a href="advice-on-regression.html#non-linear-response"><i class="fa fa-check"></i><b>12.8</b> Non linear response</a><ul>
<li class="chapter" data-level="12.8.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-5"><i class="fa fa-check"></i><b>12.8.1</b> Advice on writing up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html"><i class="fa fa-check"></i><b>13</b> Crib sheet for regression and ANOVA</a><ul>
<li class="chapter" data-level="13.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#introduction-4"><i class="fa fa-check"></i><b>13.1</b> Introduction</a><ul>
<li class="chapter" data-level="13.1.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#packages-needed"><i class="fa fa-check"></i><b>13.1.1</b> Packages needed</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#loading-the-data"><i class="fa fa-check"></i><b>13.2</b> Loading the data</a></li>
<li class="chapter" data-level="13.3" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#finding-out-about-the-data"><i class="fa fa-check"></i><b>13.3</b> Finding out about the data</a></li>
<li class="chapter" data-level="13.4" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#making-your-data-available-to-others"><i class="fa fa-check"></i><b>13.4</b> Making your data available to others</a><ul>
<li class="chapter" data-level="13.4.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#note-this-only-works-as-an-html-document"><i class="fa fa-check"></i><b>13.4.1</b> NOTE THIS ONLY WORKS AS AN HTML DOCUMENT</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#subsetting"><i class="fa fa-check"></i><b>13.5</b> Subsetting</a></li>
<li class="chapter" data-level="13.6" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#data-summaries-for-individual-variables"><i class="fa fa-check"></i><b>13.6</b> Data summaries for individual variables</a></li>
<li class="chapter" data-level="13.7" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#individual-statistics-for-a-single-variable"><i class="fa fa-check"></i><b>13.7</b> Individual statistics for a single variable</a></li>
<li class="chapter" data-level="13.8" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#simple-boxplot-of-one-variable"><i class="fa fa-check"></i><b>13.8</b> Simple boxplot of one variable</a></li>
<li class="chapter" data-level="13.9" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#simple-histogram-of-one-variable"><i class="fa fa-check"></i><b>13.9</b> Simple histogram of one variable</a></li>
<li class="chapter" data-level="13.10" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#neater-histogram-of-one-variable"><i class="fa fa-check"></i><b>13.10</b> Neater histogram of one variable</a></li>
<li class="chapter" data-level="13.11" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#regression-2"><i class="fa fa-check"></i><b>13.11</b> Regression</a></li>
<li class="chapter" data-level="13.12" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#scatterplot-without-fitted-line"><i class="fa fa-check"></i><b>13.12</b> Scatterplot without fitted line</a></li>
<li class="chapter" data-level="13.13" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#scatterplot-with-fitted-line-and-labels"><i class="fa fa-check"></i><b>13.13</b> Scatterplot with fitted line and labels</a></li>
<li class="chapter" data-level="13.14" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-a-model-1"><i class="fa fa-check"></i><b>13.14</b> Fitting a model</a></li>
<li class="chapter" data-level="13.15" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#extracting-residuals"><i class="fa fa-check"></i><b>13.15</b> Extracting residuals</a></li>
<li class="chapter" data-level="13.16" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-summary"><i class="fa fa-check"></i><b>13.16</b> Model summary</a></li>
<li class="chapter" data-level="13.17" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-anova-table"><i class="fa fa-check"></i><b>13.17</b> Model anova table</a></li>
<li class="chapter" data-level="13.18" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#confidence-intervals-for-the-model-parameters"><i class="fa fa-check"></i><b>13.18</b> Confidence intervals for the model parameters</a><ul>
<li class="chapter" data-level="13.18.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-diagnostics"><i class="fa fa-check"></i><b>13.18.1</b> Model diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="13.19" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#spearmans-rank-correlation-1"><i class="fa fa-check"></i><b>13.19</b> Spearman’s rank correlation</a><ul>
<li class="chapter" data-level="13.19.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-a-spline"><i class="fa fa-check"></i><b>13.19.1</b> Fitting a spline</a></li>
</ul></li>
<li class="chapter" data-level="13.20" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#one-way-anova"><i class="fa fa-check"></i><b>13.20</b> One way ANOVA</a><ul>
<li class="chapter" data-level="13.20.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#grouped-boxplots"><i class="fa fa-check"></i><b>13.20.1</b> Grouped boxplots</a></li>
</ul></li>
<li class="chapter" data-level="13.21" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#histograms-for-each-factor-level"><i class="fa fa-check"></i><b>13.21</b> Histograms for each factor level</a></li>
<li class="chapter" data-level="13.22" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#confidence-interval-plot"><i class="fa fa-check"></i><b>13.22</b> Confidence interval plot</a></li>
<li class="chapter" data-level="13.23" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-anova"><i class="fa fa-check"></i><b>13.23</b> Fitting ANOVA</a></li>
<li class="chapter" data-level="13.24" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#tukey-corrected-pairwise-comparisons"><i class="fa fa-check"></i><b>13.24</b> Tukey corrected pairwise comparisons</a></li>
<li class="chapter" data-level="13.25" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#anova-with-whites-correction"><i class="fa fa-check"></i><b>13.25</b> Anova with White’s correction</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html"><i class="fa fa-check"></i><b>14</b> Crib sheet for GIS in R</a><ul>
<li class="chapter" data-level="14.1" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#introduction-5"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-in-a-shapefile"><i class="fa fa-check"></i><b>14.2</b> Reading in a shapefile</a></li>
<li class="chapter" data-level="14.3" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#transforming-to-british-national-grid"><i class="fa fa-check"></i><b>14.3</b> Transforming to British National Grid</a></li>
<li class="chapter" data-level="14.4" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#mapview-of-a-polygon-layer"><i class="fa fa-check"></i><b>14.4</b> Mapview of a polygon layer</a></li>
<li class="chapter" data-level="14.5" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#adding-an-overview-map"><i class="fa fa-check"></i><b>14.5</b> Adding an overview map</a></li>
<li class="chapter" data-level="14.6" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#adding-a-measurement-tool"><i class="fa fa-check"></i><b>14.6</b> Adding a measurement tool</a></li>
<li class="chapter" data-level="14.7" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-in-points-from-a-csv"><i class="fa fa-check"></i><b>14.7</b> Reading in points from a CSV</a></li>
<li class="chapter" data-level="14.8" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-raster-data"><i class="fa fa-check"></i><b>14.8</b> Reading raster data</a></li>
<li class="chapter" data-level="14.9" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#making-colour-ramps-for-raster-data"><i class="fa fa-check"></i><b>14.9</b> Making colour ramps for raster data</a></li>
<li class="chapter" data-level="14.10" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#extracting-raster-values-for-points"><i class="fa fa-check"></i><b>14.10</b> Extracting raster values for points</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="hengistbury.html"><a href="hengistbury.html"><i class="fa fa-check"></i><b>15</b> Hengistbury</a></li>
<li class="chapter" data-level="16" data-path="arne-data-quick-load.html"><a href="arne-data-quick-load.html"><i class="fa fa-check"></i><b>16</b> Arne data quick load</a><ul>
<li class="chapter" data-level="16.1" data-path="arne-data-quick-load.html"><a href="arne-data-quick-load.html#introduction-6"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="arne-2019.html"><a href="arne-2019.html"><i class="fa fa-check"></i><b>17</b> Arne 2019</a><ul>
<li class="chapter" data-level="17.1" data-path="arne-2019.html"><a href="arne-2019.html#loading-the-waypoints"><i class="fa fa-check"></i><b>17.1</b> Loading the waypoints</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><i class="fa fa-check"></i><b>18</b> Regression analysis using measurements on individual pines from the Arne 2019 data</a><ul>
<li class="chapter" data-level="18.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#introduction-7"><i class="fa fa-check"></i><b>18.1</b> Introduction</a><ul>
<li class="chapter" data-level="18.1.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#load-r-libraries"><i class="fa fa-check"></i><b>18.1.1</b> Load R libraries</a></li>
<li class="chapter" data-level="18.1.2" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#load-the-data"><i class="fa fa-check"></i><b>18.1.2</b> Load the data</a></li>
<li class="chapter" data-level="18.1.3" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#looking-at-the-data"><i class="fa fa-check"></i><b>18.1.3</b> Looking at the data</a></li>
<li class="chapter" data-level="18.1.4" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#simple-base-r-figures"><i class="fa fa-check"></i><b>18.1.4</b> Simple base R figures</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#scatterplots-1"><i class="fa fa-check"></i><b>18.2</b> Scatterplots</a></li>
<li class="chapter" data-level="18.3" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#regression-vs-correlation-analysis"><i class="fa fa-check"></i><b>18.3</b> Regression vs correlation analysis</a><ul>
<li class="chapter" data-level="18.3.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#spline-and-line-analysis"><i class="fa fa-check"></i><b>18.3.1</b> Spline and line analysis</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#fitting-a-regression"><i class="fa fa-check"></i><b>18.4</b> Fitting a regression</a></li>
<li class="chapter" data-level="18.5" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#fitting-a-gam"><i class="fa fa-check"></i><b>18.5</b> Fitting a GAM</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><i class="fa fa-check"></i><b>19</b> Analysing the residuals from regression analysis on individual pines from the Arne 2019 data</a><ul>
<li class="chapter" data-level="19.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#introduction-8"><i class="fa fa-check"></i><b>19.1</b> Introduction</a><ul>
<li class="chapter" data-level="19.1.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#load-r-libraries-1"><i class="fa fa-check"></i><b>19.1.1</b> Load R libraries</a></li>
<li class="chapter" data-level="19.1.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#load-the-data-1"><i class="fa fa-check"></i><b>19.1.2</b> Load the data</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#adding-the-gps-points-to-the-pines"><i class="fa fa-check"></i><b>19.2</b> Adding the GPS points to the pines</a></li>
<li class="chapter" data-level="19.3" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#looking-at-the-residual"><i class="fa fa-check"></i><b>19.3</b> Looking at the residual</a><ul>
<li class="chapter" data-level="19.3.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#plotting-the-data-by-site"><i class="fa fa-check"></i><b>19.3.1</b> Plotting the data by site</a></li>
<li class="chapter" data-level="19.3.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#obtaining-residuals"><i class="fa fa-check"></i><b>19.3.2</b> Obtaining residuals</a></li>
<li class="chapter" data-level="19.3.3" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#plotting-the-residuals-by-site"><i class="fa fa-check"></i><b>19.3.3</b> Plotting the residuals by site</a></li>
<li class="chapter" data-level="19.3.4" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#confidence-intervals-1"><i class="fa fa-check"></i><b>19.3.4</b> Confidence intervals</a></li>
<li class="chapter" data-level="19.3.5" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#simple-unpaired-t-test"><i class="fa fa-check"></i><b>19.3.5</b> Simple unpaired t-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html"><i class="fa fa-check"></i><b>20</b> Mapping and analysing pine densities at Arne</a><ul>
<li class="chapter" data-level="20.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#introduction-9"><i class="fa fa-check"></i><b>20.1</b> Introduction</a><ul>
<li class="chapter" data-level="20.1.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#loading-libraries"><i class="fa fa-check"></i><b>20.1.1</b> Loading libraries</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#loading-the-data-1"><i class="fa fa-check"></i><b>20.2</b> Loading the data</a><ul>
<li class="chapter" data-level="20.2.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#points-to-notice"><i class="fa fa-check"></i><b>20.2.1</b> Points to notice</a></li>
<li class="chapter" data-level="20.2.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#making-a-spatial-object-in-r"><i class="fa fa-check"></i><b>20.2.2</b> Making a spatial object in R</a></li>
<li class="chapter" data-level="20.2.3" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action"><i class="fa fa-check"></i><b>20.2.3</b> Action</a></li>
<li class="chapter" data-level="20.2.4" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#comparing-density-in-the-heathland-and-restoration-site."><i class="fa fa-check"></i><b>20.2.4</b> Comparing density in the heathland and restoration site.</a></li>
<li class="chapter" data-level="20.2.5" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#question-how-does-the-pine-density-differ-between-the-heathland-and-the-restoration-site"><i class="fa fa-check"></i><b>20.2.5</b> Question: How does the pine density differ between the heathland and the restoration site?</a></li>
<li class="chapter" data-level="20.2.6" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#boxplot-of-pine-density"><i class="fa fa-check"></i><b>20.2.6</b> Boxplot of pine density</a></li>
<li class="chapter" data-level="20.2.7" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-1"><i class="fa fa-check"></i><b>20.2.7</b> Action</a></li>
<li class="chapter" data-level="20.2.8" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#inferential-confidence-interval-plot"><i class="fa fa-check"></i><b>20.2.8</b> Inferential confidence interval plot</a></li>
<li class="chapter" data-level="20.2.9" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-2"><i class="fa fa-check"></i><b>20.2.9</b> Action</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#section"><i class="fa fa-check"></i><b>20.3</b> ——————————————————-</a></li>
<li class="chapter" data-level="20.4" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#investigating-factors-affecting-pine-densities-on-the-heathland-site"><i class="fa fa-check"></i><b>20.4</b> Investigating factors affecting pine densities on the heathland site</a></li>
<li class="chapter" data-level="20.5" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#spatial-data"><i class="fa fa-check"></i><b>20.5</b> Spatial data</a><ul>
<li class="chapter" data-level="20.5.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#cropping"><i class="fa fa-check"></i><b>20.5.1</b> Cropping</a></li>
<li class="chapter" data-level="20.5.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#terrain-analysis-1"><i class="fa fa-check"></i><b>20.5.2</b> Terrain analysis</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#raster-algebra"><i class="fa fa-check"></i><b>20.6</b> Raster algebra</a></li>
<li class="chapter" data-level="20.7" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#raster-aggregation"><i class="fa fa-check"></i><b>20.7</b> Raster aggregation</a><ul>
<li class="chapter" data-level="20.7.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-3"><i class="fa fa-check"></i><b>20.7.1</b> Action</a></li>
</ul></li>
<li class="chapter" data-level="20.8" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#adding-the-values-to-the-quadrats"><i class="fa fa-check"></i><b>20.8</b> Adding the values to the quadrats</a></li>
<li class="chapter" data-level="20.9" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#distances-to-trees"><i class="fa fa-check"></i><b>20.9</b> Distances to trees</a></li>
<li class="chapter" data-level="20.10" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#data-table"><i class="fa fa-check"></i><b>20.10</b> Data table</a></li>
<li class="chapter" data-level="20.11" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#writing-out-the-data"><i class="fa fa-check"></i><b>20.11</b> Writing out the data</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html"><i class="fa fa-check"></i><b>21</b> Statistical analysis of the pine density data</a><ul>
<li class="chapter" data-level="21.1" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#introduction-10"><i class="fa fa-check"></i><b>21.1</b> Introduction</a><ul>
<li class="chapter" data-level="21.1.1" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#loading-libraries-1"><i class="fa fa-check"></i><b>21.1.1</b> Loading libraries</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#running-analyses"><i class="fa fa-check"></i><b>21.2</b> Running analyses</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative and spatial analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-one-way-anova" class="section level1">
<h1><span class="header-section-number">Chapter 10</span> Introduction to one way ANOVA</h1>
<p>In the last class we looked at the basis for inferential statistics. You saw how the the standard deviation can be calculated for a sample of measurements taken from a larger population and how this can be used to “infer” a confidence interval within which we would expect the population mean to fall 95% of the time. This concept also was used to test hypotheses regarding the differences between two means using a t-test.</p>
<p>This class introduces some simple model based analyses. We will look at some data on mussel shell lengths taken from 6 different sites. The simple question to answer is if any of the overall variability can be attributed to the differences between the sites. This is a simple example of one way analysis of variance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d&lt;-<span class="kw">read.csv</span>(<span class="st">&quot;https://tinyurl.com/aqm-data/mussels.csv&quot;</span>)</code></pre></div>
<div id="multiple-comparisons" class="section level3">
<h3><span class="header-section-number">10.0.1</span> Multiple comparisons</h3>
<p>A t-test involves comparisons between two means. You can use R to find out how many combinations of pairs of sites there would be using binomial theory.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(d<span class="op">$</span>Site)</code></pre></div>
<pre><code>## [1] &quot;Site_1&quot; &quot;Site_2&quot; &quot;Site_3&quot; &quot;Site_4&quot; &quot;Site_5&quot; &quot;Site_6&quot;</code></pre>
<p>There are 6 levels. Choosing combinations of two from six.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">choose</span>(<span class="dv">6</span>,<span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 15</code></pre>
<p>Running 15 separate t-tests would be quite a lot of work. So in this sort of case we often ask a more general question first. We test whether there is any significant differences between any of the sites.</p>
</div>
<div id="visualising-between-group-variation-using-boxplots" class="section level3">
<h3><span class="header-section-number">10.0.2</span> Visualising between group variation using boxplots</h3>
<p>A good first step is to look at the variation in the data for each site using boxplots. If we use the plotly library in R we obtain dynamic boxplots.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(plotly)
<span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())
g0 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d,<span class="kw">aes</span>(<span class="dt">x=</span>Site,<span class="dt">y=</span>Lshell))
g_box&lt;-g0<span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()
<span class="kw">ggplotly</span>(g_box)</code></pre></div>
<div id="5fb97c13cc44" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="5fb97c13cc44">{"x":{"data":[{"x":[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],"y":[122.1,100.1,100.7,102.3,94.9,116.9,94.9,91.5,94.3,85.6,113.5,111.5,106,115.5,101.1,97.4,89.2,121.1,95.8,94.7,108.6,100.2,107.2,112.6,103.3,118.9,61.9,124.7,132.55,91.1,125.6,110.1,89.6,127.7,102.4,93.5,113.8,102.8,93.9,73.8,69.3,120.9,131.7,129.9,120.4,128,114.2,128.4,120.7,116.3,110.7,105.5,120.5,123.2,124.2,125.6,118.6,104.2,116.7,132.2,115.8,101.1,110,102.3,84.1,96.4,99.5,89.8,81.7,125.9,124.3,99.5,104.1,111.9,102.2,92.1,83.9,97,113.9,108.2,106.4,102.6,99.6,90.8,118.4,97,76.6,101.8,122.8,104.9,121.5,124.2,118.9,117.4,77.5,130.6,79.3,116.8,119.5,99.5,115.2,118.7,109.2,118.3,113.8,106.9,113.4,99.8,96.8,121.1,94.3,102.4,88.1],"hoverinfo":"y","type":"box","fillcolor":"rgba(255,255,255,1)","marker":{"opacity":null,"outliercolor":"rgba(0,0,0,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)"},"size":5.66929133858268},"line":{"color":"rgba(51,51,51,1)","width":1.88976377952756},"showlegend":false,"xaxis":"x","yaxis":"y","frame":null}],"layout":{"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xaxis":{"domain":[0,1],"type":"linear","autorange":false,"range":[0.4,6.6],"tickmode":"array","ticktext":["Site_1","Site_2","Site_3","Site_4","Site_5","Site_6"],"tickvals":[1,2,3,4,5,6],"categoryorder":"array","categoryarray":["Site_1","Site_2","Site_3","Site_4","Site_5","Site_6"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":"Site","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"type":"linear","autorange":false,"range":[58.3675,136.0825],"tickmode":"array","ticktext":["60","80","100","120"],"tickvals":[60,80,100,120],"categoryorder":"array","categoryarray":["60","80","100","120"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"x","title":"Lshell","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"source":"A","attrs":{"5fb93e3d32e3":{"x":{},"y":{},"type":"box"}},"cur_data":"5fb93e3d32e3","visdat":{"5fb93e3d32e3":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1}},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":{"render":[{"code":"function(el, x) { var ctConfig = crosstalk.var('plotlyCrosstalkOpts').set({\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1}}); }","data":null}]}}</script>
</div>
<div id="boxplot-statistics" class="section level3">
<h3><span class="header-section-number">10.0.3</span> Boxplot statistics</h3>
<p>Hovering over the boxplots shows some key statistic for each group. The central line in the boxplot is the median. The box holds the interquartile range (i.e. 50% of the observations fall within it). The whiskers extend out to the what is, informally speaking, either the upper or lower limits to the distribution or the upper or lower limits expected if the data are normally distributed. Thus boxplots are useful as diagnostic tools to identify outliers or skewed distributions.</p>
<p>The problem with comparing data using boxplots is that they show all the variability in the data, so there is often a large overlap between the boxes.</p>
</div>
<div id="plotting-confidence-intervals-for-each-group" class="section level3">
<h3><span class="header-section-number">10.0.4</span> Plotting confidence intervals for each group</h3>
<p>The standard error for the mean and the confidence intervals for the mean that are calculated from it are a function of sample size. So we may want to plot the confidence intervals for the mean in order to spot differences more clearly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">g_mean&lt;-g0<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean,<span class="dt">geom=</span><span class="st">&quot;point&quot;</span>)
g_mean&lt;-g_mean<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_cl_normal,<span class="dt">geom=</span><span class="st">&quot;errorbar&quot;</span>)
g_mean</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-123-1.png" width="672" /></p>
<p>If there is clear space between confidence intervals a significance test will be significant. If confidence intervals overlap slightly the test may, or may not be significant depending on the extent of the overlap. If the overlap is large the tests will never be significant.</p>
<p>Combining the two. This looks a bit messy visually, but helps to show the relationship between boxplots and confidence intervals.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">g_mean&lt;-g_box<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean,<span class="dt">geom=</span><span class="st">&quot;point&quot;</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)
g_mean<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_cl_normal,<span class="dt">geom=</span><span class="st">&quot;errorbar&quot;</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-124-1.png" width="672" /></p>
</div>
<div id="fitting-a-model" class="section level3">
<h3><span class="header-section-number">10.0.5</span> Fitting a model</h3>
<p>We can test a simple hypothesis using a technique called <strong>one way ANOVA</strong>. Could the variation in means between sites simply be due to chance? To do that we compare the variability in means to the overall variability in the data.</p>
<p>Crawley’s R book provides an in depth explanation of the logic behind analysis of variance in chapter 9. I will not repeat all the details today. Next week we will look at where the sum of squares come from in linear models in the case of both anova and regression.</p>
<p>In R to fit the analysis of variance as a model we can write aov(Lshell~Site) and then ask for a summary.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">aov</span>(<span class="dt">data=</span>d,Lshell<span class="op">~</span>Site)
<span class="kw">summary</span>(mod)</code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Site          5   5525    1105   6.173 4.58e-05 ***
## Residuals   107  19153     179                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The result suggests that there is significant variation in mean shell length between sites, providing the assumptions of the test hold.</p>
</div>
<div id="the-f-ratio-and-degrees-of-freedom" class="section level3">
<h3><span class="header-section-number">10.0.6</span> The F ratio and degrees of freedom</h3>
<p>The key to understanding analysis of variance is to understand the F ratio. The calculations produce a sum of squares and a mean square that are attributed to two sources of variation in the data. For this reason we often talk about <strong>partitioning the variance</strong>. The Site component is the amount of variation attributable to variations in the mean shell lengths between sites. The residual variation is the amount of variability around these mean values. You can see that the mean square for the Site term in the model is much larger than the mean square for the Residuals term. In fact it is just over <strong>6</strong> times larger. We know that because the table includes the <strong>F value</strong>, which is the <strong>ratio</strong> of the two mean squares. The table also contains information regarding the number of groups and the amount of replication. These are the degrees of freedom. The degrees of freedom for Site is n-1. There are six sites so there are five degrees of freedom. The degrees of freedom for the residuals are the total number of measurements minus the number of sites (factor levels). So we have 113-6=107. If you are wondering how this works, the simple explanation is that we subtract the number of mean values that we use in the calculation of the sum of squares. In the case of the site, one overall mean is used (nsites-1). In the case of the residuals the mean of each site is subtracted from the observations for each site (nobs-6).</p>
<p>So we can now make a formal statement that we back up with the statistical analysis. We write that <strong>There is statistically significant variability in mean shell lengths between sites F(5, 107) = 6.17, p &lt;0.001.</strong></p>
</div>
<div id="homogeneity-of-variance" class="section level3">
<h3><span class="header-section-number">10.0.7</span> Homogeneity of variance</h3>
<p>You might have spotted an issue with this test, particularly if you have been reading the text books thoroughly. The traditional analysis of variance assumes homogeneity of variances. The boxplots suggest that there is a lot of variation in between sites in the amount of variation in shell length. A test for homogeneity of variance that is often recommended is Bartlett’s test</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">bartlett.test</span>(d<span class="op">$</span>Lshell<span class="op">~</span>d<span class="op">$</span>Site) </code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  d$Lshell by d$Site
## Bartlett&#39;s K-squared = 18.528, df = 5, p-value = 0.002352</code></pre>
<p>As always, a low p-value suggests that the null hypothesis can be rejected, which in this case is homogeneity of variances. So on technical grounds the test we have just conducted is not quite right. One of the assumptions is not met. This can be a major issue for more complex designs. It is easy to let R make a correction for this when running a one way anova by asking for a oneway test (Welch’s test).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">oneway.test</span>(d<span class="op">$</span>Lshell<span class="op">~</span>d<span class="op">$</span>Site) </code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  d$Lshell and d$Site
## F = 9.6559, num df = 5.000, denom df = 31.194, p-value = 1.207e-05</code></pre>
<p>The test has now taken into account the issue and it still gives a significant result. Using Welch’s procedure is a useful backup to reinforce and defend your conclusions when the assumption of homogeneity of variance is violated. We will look at this and similar issues in more detail in the course. However you still need to look at the pattern of differences more carefully.</p>
</div>
<div id="alternative-to-the-one-way-test" class="section level2">
<h2><span class="header-section-number">10.1</span> Alternative to the one way test</h2>
<p>Another slightly more sophisticated way of handling homogenity of variance in R is to use a procedure called White’s adjustment.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sandwich)
<span class="kw">library</span>(car)</code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:boot&#39;:
## 
##     logit</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(Lshell<span class="op">~</span>Site, <span class="dt">data=</span>d)
<span class="kw">Anova</span>(mod,<span class="dt">white.adjust=</span><span class="st">&#39;hc3&#39;</span>)</code></pre></div>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: Lshell
##            Df      F    Pr(&gt;F)    
## Site        5 9.9682 7.541e-08 ***
## Residuals 107                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The F ratio after making an appropriate correction is actually rather higher.</p>
<p><em>Write down a statement that you could include in a report that expresses this formally</em></p>
<p>It should begin along these lines …</p>
<p>“Bartlet’s test showed significant heteroscedasticity in the residuals for all metals. White-corrected covariance matrices were therefore be included in a linear model in order to adjust for lack of homogeneity. Corrected one way Anova showed …”</p>
<div id="determining-where-the-differences-lie" class="section level3">
<h3><span class="header-section-number">10.1.1</span> Determining where the differences lie</h3>
<p>There is a problem with the simple conclusion drawn from analysis of variance with or without correction. From a scientific perspective is it is hardly an unsurprising discovery. We would have expected some difference between sites, particularly if we look at so many different places. It is much more likely that we are really interested in <strong>specific</strong> differences between sites. However this raises an additional issue. If we have a hypothesis before we start regarding which site is most likely to be different we could run one single test. However if we are looking at fifteen separate comparisons that is a problem. The conventional significance value is set at 0.05. In other words one chance in twenty of obtaining the data (or more extreme) under the null hypothesis. If we run a lot of tests we increase the chances of at least one being significant even if the null holds.</p>
<p>In fact it is quite easy to calculate the probability of getting at least one significant result if we run 15 tests. The easy way is to calculate the probability of all the tests being negative and subtract from 1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">-</span><span class="fl">0.95</span><span class="op">^</span><span class="dv">15</span></code></pre></div>
<pre><code>## [1] 0.5367088</code></pre>
<p>So there is a 54% chance of getting at least one significant result at the 0.05 cut off level even if the null is true for every comparison. This is a bit like buying a large number of lottery tickets. If you buy enough you increase your overall chances of winning even though the chances of any single ticket winning remains the same.</p>
<p><em>What is the probability of getting at least one significant result at the 0.05 level if you run twenty tests? Without thinking it is tempting to say that it is one. However this is not the correct answer. Try calculating it.</em></p>
<p>One way of reducing the number of tests is to compare all the means with a control group. This is done in an experiment with treatments, and is the contrasts are thus known as treatment contrasts. We can obtain these in R from the output of aov using summary.lm.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary.lm</span>(mod) </code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Lshell ~ Site, data = d)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.906  -8.340   1.031   9.231  30.550 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  100.769      2.624  38.405  &lt; 2e-16 ***
## SiteSite_2     8.467      3.748   2.259   0.0259 *  
## SiteSite_3     6.037      5.409   1.116   0.2669    
## SiteSite_4    -3.619      5.409  -0.669   0.5049    
## SiteSite_5    18.697      3.925   4.763 6.02e-06 ***
## SiteSite_6     2.471      3.748   0.659   0.5111    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.38 on 107 degrees of freedom
## Multiple R-squared:  0.2239, Adjusted R-squared:  0.1876 
## F-statistic: 6.173 on 5 and 107 DF,  p-value: 4.579e-05</code></pre>
<p>This shows that only site2 and site5 are significantly different from site 1. If you go back to the confidence interval plot and look at the overlap you can see how this pattern emerges.</p>
</div>
<div id="bonferoni-corrections" class="section level3">
<h3><span class="header-section-number">10.1.2</span> Bonferoni corrections</h3>
<p>Treatment contrasts method assumes that there is a planned contrast and there is something unique about site1. Another way of looking at the issue is to effectively make comparisons between all the pairs of sites. In this case we MUST compensate in some way for all the test. There are a lot of ways of doing this. The simplest is called the Bonferoni correction. This just involves changing the critical value by dividing by the number of tests. So if we call a p-value of 0.05 significant, but run 15 tests we would look for values of 0.05/15= 0.0033 before claiming a significant result.</p>
</div>
<div id="tukeys-honest-significant-difference" class="section level3">
<h3><span class="header-section-number">10.1.3</span> Tukey’s honest significant difference</h3>
<p>A slightly more subtle method is called Tukey’s Honest Significant Difference (HSD) test. We can run this in R for all pairwise comparisons and plot the results. The confidence intervals and p-values are all adjusted.</p>
<p>This produces a lot of output, as you would expect. It effectively runs the fifteen separate t-tests while making allowances for multiple comparisons. The output also includes 95% confidence intervals for the differences between the means. If these confidence intervals include zero then the test will not be significant. The easiest way to see the pattern is to plot the results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">aov</span>(<span class="dt">data=</span>d,Lshell<span class="op">~</span>Site)
<span class="kw">TukeyHSD</span>(mod)</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Lshell ~ Site, data = d)
## 
## $Site
##                     diff        lwr       upr     p adj
## Site_2-Site_1   8.466769  -2.408905 19.342443 0.2201442
## Site_3-Site_1   6.037019  -9.660664 21.734702 0.8737518
## Site_4-Site_1  -3.619231 -19.316914 12.078452 0.9849444
## Site_5-Site_1  18.697436   7.305950 30.088922 0.0000867
## Site_6-Site_1   2.470769  -8.404905 13.346443 0.9859123
## Site_3-Site_2  -2.429750 -18.201132 13.341632 0.9976925
## Site_4-Site_2 -12.086000 -27.857382  3.685382 0.2355928
## Site_5-Site_2  10.230667  -1.262165 21.723498 0.1103764
## Site_6-Site_2  -5.996000 -16.977781  4.985781 0.6105029
## Site_4-Site_3  -9.656250 -29.069479  9.756979 0.7004668
## Site_5-Site_3  12.660417  -3.470986 28.791819 0.2123990
## Site_6-Site_3  -3.566250 -19.337632 12.205132 0.9862071
## Site_5-Site_4  22.316667   6.185264 38.448069 0.0015143
## Site_6-Site_4   6.090000  -9.681382 21.861382 0.8718474
## Site_6-Site_5 -16.226667 -27.719498 -4.733835 0.0011239</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">TukeyHSD</span>(mod))</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-131-1.png" width="672" /></p>
<p>Notice that the comparison that we made between site1 and site2 that was significant using either a single t-test or treatment contrasts now is not shown as significant after the correction has been made for making numerous unplanned comparisons. If you really wanted to claim that the difference was significant you would have to be able to justify that you had thought that site2 ought to be particularly different before obtaining the data, and that the result was not just obtained by so called ``data dredging’’.</p>
<p>So, there are some rather subtle aspects of data analysis. Under the more rigorous procedure only site 5 really stands out as being different from the rest. The fact that different ways of looking at the data can apparently lead to different conclusions is one of the aspects of statistics that worries many students (and researchers). Next term we will look at ways of avoiding common statistical pitfalls, together with methods to extract all the important information from a data set in order to fully address your scientific question.</p>
</div>
<div id="the-kruskal-wallace-non-parametric-test." class="section level3">
<h3><span class="header-section-number">10.1.4</span> The Kruskal Wallace non parametric test.</h3>
<p>The Kruskal Wallace test is often used in place of a one way anova when researchers are worried about the assumption of normality and want to use a non-parametric procedure. The disadvantage of a Kruskall Wallace test is that it is not easy to communicate the absolute size of any differences that are detected. The test does not lead to the development of a statistical model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">kruskal.test</span>(d<span class="op">$</span>Lshell<span class="op">~</span>d<span class="op">$</span>Site) </code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  d$Lshell by d$Site
## Kruskal-Wallis chi-squared = 27.884, df = 5, p-value = 3.835e-05</code></pre>
<p>The diffferences refer to the location parameter, which is similar to the median, but not exactly the same measurement. This is difficult to communicate. Another tactic is to bootstrap the median itself. We saw how bootstrapping can be used last week. I have provided a small function to do this that can be used with a ggplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">median_cl_boot &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">conf =</span> <span class="fl">0.95</span>) {
    lconf &lt;-<span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>conf)<span class="op">/</span><span class="dv">2</span>
    uconf &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>lconf
    <span class="kw">require</span>(boot)
    bmedian &lt;-<span class="st"> </span><span class="cf">function</span>(x, ind) <span class="kw">median</span>(x[ind])
    bt &lt;-<span class="st"> </span><span class="kw">boot</span>(x, bmedian, <span class="dv">1000</span>)
    bb &lt;-<span class="st"> </span><span class="kw">boot.ci</span>(bt, <span class="dt">type =</span> <span class="st">&quot;perc&quot;</span>)
    <span class="kw">data.frame</span>(<span class="dt">y =</span> <span class="kw">median</span>(x), <span class="dt">ymin =</span> <span class="kw">quantile</span>(bt<span class="op">$</span>t, lconf), <span class="dt">ymax =</span> <span class="kw">quantile</span>(bt<span class="op">$</span>t, 
        uconf))
}

g0<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>median_cl_boot,<span class="dt">geom=</span><span class="st">&quot;errorbar&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.y =</span> median, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p><em>How do you interpret this figure?</em></p>
</div>
</div>
<div id="power-analysis" class="section level2">
<h2><span class="header-section-number">10.2</span> Power analysis</h2>
<p>Power analysis should always be caaried out when designing any study that involves one way analysis of variance. It is very easy to do.</p>
<p>The idea behind a power analysis is to “reverse engineer” the analysis of variance.</p>
<p>Usually when we carry out analysis of variance we want to show that there is some difference between groups. However if the sample size is too small we might not be able to reject the null hypothesis. The null hypothesis is that the observations could all have been drawn from the same population. Any difference between means is just down to chance variability that arises from variability within the groups.</p>
<p>Power analysis asks a “what if” question. If you have a small pilot study you might be able to provide the parameters for the question.</p>
<p>Let’s set up a scenario involving four groups. We can either guess some rough estimates of the group means why might expect, find some literature on the subject or carry out a small pilot study to provide some data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">groupmeans &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">120</span>, <span class="dv">130</span>, <span class="dv">140</span>, <span class="dv">150</span>)
n&lt;-<span class="kw">length</span>(groupmeans)
bvar&lt;-<span class="kw">var</span>(groupmeans)</code></pre></div>
<p>Notice that we need to calculate the variance between the group means and get the number of groups.</p>
<p>We then need to estimate the standard deviation. The best way to do this is through a short pilot study, but we can also make some informed assumptions regarding the value. The within sample variance is just this value squared.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sdev&lt;-<span class="dv">20</span>

wvar&lt;-sdev<span class="op">^</span><span class="dv">2</span></code></pre></div>
<p>So the number of groups is 4. The variance between the the group means is calculated from the four observations and is 166.7. We estimate the standard deviation (think in terms of how far from the mean would you expect 66% of the observations to lie).</p>
<p>Now we can set the power to the alpha level we want. If the power is set to 0.9 we would expect to find a significant difference in 90% of the studies, but we might obtain a type 2 error 10% of the time. A type two error is when we fail to reject the null hypothesis when it is in fact false, or in other words not find a significant difference even though it does exist.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha&lt;-<span class="fl">0.9</span>
<span class="kw">power.anova.test</span>(<span class="dt">groups =</span> n, <span class="dt">between.var =</span> bvar, <span class="dt">within.var =</span> wvar, <span class="dt">power =</span> alpha)</code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##          groups = 4
##               n = 12.3635
##     between.var = 166.6667
##      within.var = 400
##       sig.level = 0.05
##           power = 0.9
## 
## NOTE: n is number in each group</code></pre>
</div>
<div id="exercise-5" class="section level2">
<h2><span class="header-section-number">10.3</span> Exercise</h2>
<p>Design a study to test whether there is a significant difference between the lengths of oak leaves collected from trees on the campus.</p>
<p>Your first task is to collect a small sample and design a power analysis.</p>
</div>
<div id="references" class="section level2">
<h2><span class="header-section-number">10.4</span> References</h2>
<p>Long, J. S. and Ervin, L. H. (2000) Using heteroscedasity consistent standard errors in the linear regression model. The American Statistician 54, 217–224. <a href="http://www.jstor.org/stable/2685594" class="uri">http://www.jstor.org/stable/2685594</a></p>
<p>White, H. (1980) A heteroskedastic consistent covariance matrix estimator and a direct test of heteroskedasticity. Econometrica 48, 817–838.</p>
<p>Fox, J. (2008) Applied Regression Analysis and Generalized Linear Models, Second Edition. Sage.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="t-tests-and-hypothesis-testing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression-as-a-statistical-modelling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["Quantitative_and_Spatial.pdf", "Quantitative_and_Spatial.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
