<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 11 Regression as a statistical modelling | Quantitative and spatial analysis</title>
  <meta name="description" content="Chapter 11 Regression as a statistical modelling | Quantitative and spatial analysis">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 11 Regression as a statistical modelling | Quantitative and spatial analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Regression as a statistical modelling | Quantitative and spatial analysis" />
  
  
  

<meta name="author" content="Duncan Golicher">


<meta name="date" content="2019-12-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduction-to-one-way-anova.html">
<link rel="next" href="advice-on-regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<script src="libs/jszip-1.10.16/jszip.min.js"></script>
<link href="libs/dt-ext-buttons-1.10.16/css/buttons.dataTables.min.css" rel="stylesheet" />
<script src="libs/dt-ext-buttons-1.10.16/js/dataTables.buttons.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.flash.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.html5.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.colVis.min.js"></script>
<script src="libs/dt-ext-buttons-1.10.16/js/buttons.print.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<link href="libs/PopupTable-0.0.1/popup.css" rel="stylesheet" />
<link href="libs/lfx-fullscreen-1.0.2/lfx-fullscreen-prod.css" rel="stylesheet" />
<script src="libs/lfx-fullscreen-1.0.2/lfx-fullscreen-prod.js"></script>
<link href="libs/leaflet-minimap-3.3.1/Control.MiniMap.min.css" rel="stylesheet" />
<script src="libs/leaflet-minimap-3.3.1/Control.MiniMap.min.js"></script>
<script src="libs/leaflet-minimap-3.3.1/Minimap-binding.js"></script>
<link href="libs/lfx-measure-path-1.3.1/lfx-measure-path-prod.css" rel="stylesheet" />
<script src="libs/lfx-measure-path-1.3.1/lfx-measure-path-prod.js"></script>
<script src="libs/lfx-measure-path-1.3.1/lfx-measure-path-bindings.js"></script>
<link href="libs/leaflet-easybutton-1.3.1/easy-button.css" rel="stylesheet" />
<script src="libs/leaflet-easybutton-1.3.1/easy-button.js"></script>
<script src="libs/leaflet-easybutton-1.3.1/EasyButton-binding.js"></script>
<link href="libs/ionicons-2.0.1/ionicons.min.css" rel="stylesheet" />
<link href="libs/leaflet-measure-2.1.7/leaflet-measure.css" rel="stylesheet" />
<script src="libs/leaflet-measure-2.1.7/leaflet-measure.min.js"></script>
<script src="libs/aspect-1/data_stars_aspecte26b50.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/dtm-1/data_stars_dtm1cb720.txt"></script>
<script src="libs/fuse_js-3.2.0/fuse_js-prod.js"></script>
<link href="libs/lfx-search-2.3.7/lfx-search-prod.css" rel="stylesheet" />
<script src="libs/lfx-search-2.3.7/lfx-search-prod.js"></script>
<script src="libs/lfx-search-2.3.7/lfx-search-bindings.js"></script>
<script src="libs/dsm-1/data_stars_dsm4d7328.txt"></script>
<script src="libs/chm10-1/data_stars_chm1086d415.txt"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative and spatial</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html"><i class="fa fa-check"></i><b>1</b> Introduction to GIS</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#what-is-a-gis"><i class="fa fa-check"></i><b>1.1</b> What is a GIS?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#desktop-gis"><i class="fa fa-check"></i><b>1.2</b> Desktop GIS</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#some-key-gis-concept"><i class="fa fa-check"></i><b>1.3</b> Some key GIS concept</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#coordinate-reference-systems-and-projections."><i class="fa fa-check"></i><b>1.3.1</b> Coordinate reference systems and projections.</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#raster-vs-vector-data"><i class="fa fa-check"></i><b>1.3.2</b> Raster vs vector data</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#making-your-own-maps"><i class="fa fa-check"></i><b>1.4</b> Making your own maps</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#the-qgis-interface"><i class="fa fa-check"></i><b>1.4.1</b> The QGIS interface</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#qgis-gui"><i class="fa fa-check"></i><b>1.4.2</b> QGIS GUI</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#adding-base-maps"><i class="fa fa-check"></i><b>1.4.3</b> Adding base maps</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#loading-a-base-map"><i class="fa fa-check"></i><b>1.4.4</b> Loading a base map</a></li>
<li class="chapter" data-level="1.4.5" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#saving-projects-and-files"><i class="fa fa-check"></i><b>1.4.5</b> Saving projects and files</a></li>
<li class="chapter" data-level="1.4.6" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#adding-a-wcs-raster-layer-from-the-local-geoserver"><i class="fa fa-check"></i><b>1.4.6</b> Adding a WCS raster layer from the local Geoserver</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#raster-terrain-data"><i class="fa fa-check"></i><b>1.5</b> Raster terrain data</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#vector-data-from-the-wfs-service"><i class="fa fa-check"></i><b>1.6</b> Vector data from the WFS service</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-gis.html"><a href="introduction-to-gis.html#saving-layers-locally-for-processing-and-offline-use"><i class="fa fa-check"></i><b>1.7</b> Saving layers locally for processing and offline use</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html"><i class="fa fa-check"></i><b>2</b> On screen digitising</a><ul>
<li class="chapter" data-level="2.1" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#digitising-tool-bar"><i class="fa fa-check"></i><b>2.1</b> Digitising tool bar</a></li>
<li class="chapter" data-level="2.2" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#drawing-a-polygon"><i class="fa fa-check"></i><b>2.2</b> Drawing a polygon</a><ul>
<li class="chapter" data-level="2.2.1" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#valid-and-invalid-geometries"><i class="fa fa-check"></i><b>2.2.1</b> Valid and invalid geometries</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#saving-the-polygon"><i class="fa fa-check"></i><b>2.3</b> Saving the polygon</a></li>
<li class="chapter" data-level="2.4" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#snapping"><i class="fa fa-check"></i><b>2.4</b> Snapping</a></li>
<li class="chapter" data-level="2.5" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#avoiding-intersections"><i class="fa fa-check"></i><b>2.5</b> Avoiding intersections</a></li>
<li class="chapter" data-level="2.6" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#splitting-on-paths"><i class="fa fa-check"></i><b>2.6</b> Splitting on paths</a></li>
<li class="chapter" data-level="2.7" data-path="on-screen-digitising.html"><a href="on-screen-digitising.html#summary"><i class="fa fa-check"></i><b>2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html"><i class="fa fa-check"></i><b>3</b> Styling and cartography</a><ul>
<li class="chapter" data-level="3.1" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#using-a-prebuilt-style"><i class="fa fa-check"></i><b>3.2</b> Using a prebuilt style</a><ul>
<li class="chapter" data-level="3.2.1" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#finding-the-styling-dialogue"><i class="fa fa-check"></i><b>3.2.1</b> Finding the styling dialogue</a></li>
<li class="chapter" data-level="3.2.2" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#loading-the-style-sheet-colour-scheme-for-the-polygons."><i class="fa fa-check"></i><b>3.2.2</b> Loading the style sheet colour scheme for the polygons.</a></li>
<li class="chapter" data-level="3.2.3" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#filtering-the-visible-styles"><i class="fa fa-check"></i><b>3.2.3</b> Filtering the visible styles</a></li>
<li class="chapter" data-level="3.2.4" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#copying-and-pasting-styles"><i class="fa fa-check"></i><b>3.2.4</b> Copying and pasting styles</a></li>
<li class="chapter" data-level="3.2.5" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#adding-derived-attributes"><i class="fa fa-check"></i><b>3.2.5</b> Adding derived attributes</a></li>
<li class="chapter" data-level="3.2.6" data-path="styling-and-cartography.html"><a href="styling-and-cartography.html#cartography-designing-a-prinatable-map"><i class="fa fa-check"></i><b>3.2.6</b> Cartography: Designing a prinatable map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="terrain-analysis.html"><a href="terrain-analysis.html"><i class="fa fa-check"></i><b>4</b> Terrain analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#what-is-terrain-analysis"><i class="fa fa-check"></i><b>4.1</b> What is terrain analysis</a></li>
<li class="chapter" data-level="4.2" data-path="terrain-analysis.html"><a href="terrain-analysis.html#lidar-data"><i class="fa fa-check"></i><b>4.2</b> Lidar data</a></li>
<li class="chapter" data-level="4.3" data-path="terrain-analysis.html"><a href="terrain-analysis.html#working-with-lidar-data-in-qgis"><i class="fa fa-check"></i><b>4.3</b> Working with Lidar data in QGIS</a><ul>
<li class="chapter" data-level="4.3.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#analytical-hill-shading"><i class="fa fa-check"></i><b>4.3.1</b> Analytical hill shading</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="terrain-analysis.html"><a href="terrain-analysis.html#colouring-the-dtm"><i class="fa fa-check"></i><b>4.4</b> Colouring the DTM</a><ul>
<li class="chapter" data-level="4.4.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#adding-contour-lines"><i class="fa fa-check"></i><b>4.4.1</b> Adding contour lines</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-slope-and-aspect"><i class="fa fa-check"></i><b>4.5</b> Calculating slope and aspect</a><ul>
<li class="chapter" data-level="4.5.1" data-path="terrain-analysis.html"><a href="terrain-analysis.html#slope"><i class="fa fa-check"></i><b>4.5.1</b> Slope</a></li>
<li class="chapter" data-level="4.5.2" data-path="terrain-analysis.html"><a href="terrain-analysis.html#aspect"><i class="fa fa-check"></i><b>4.5.2</b> Aspect</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-canopy-height."><i class="fa fa-check"></i><b>4.6</b> Calculating canopy height.</a></li>
<li class="chapter" data-level="4.7" data-path="terrain-analysis.html"><a href="terrain-analysis.html#investigating-canopy-height-in-3d"><i class="fa fa-check"></i><b>4.7</b> Investigating canopy height in 3D</a></li>
<li class="chapter" data-level="4.8" data-path="terrain-analysis.html"><a href="terrain-analysis.html#calculating-raster-stats-for-polygons."><i class="fa fa-check"></i><b>4.8</b> Calculating raster stats for polygons.</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html"><i class="fa fa-check"></i><b>5</b> Introduction to the RStudio Server</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#getting-started-with-the-rstudio-server"><i class="fa fa-check"></i><b>5.2</b> Getting started with the RStudio server</a><ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-log-into-the-rstudio-server"><i class="fa fa-check"></i><b>5.2.1</b> Action: Log into the RStudio server</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#rstudio-server-concepts"><i class="fa fa-check"></i><b>5.3</b> RStudio server concepts</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#finding-your-way-around-the-interface"><i class="fa fa-check"></i><b>5.4</b> Finding your way around the interface</a><ul>
<li class="chapter" data-level="5.4.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#using-projects-in-rstudio"><i class="fa fa-check"></i><b>5.4.1</b> Using projects in RStudio</a></li>
<li class="chapter" data-level="5.4.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-form-a-new-project-and-add-a-new-folder"><i class="fa fa-check"></i><b>5.4.2</b> Action: Form a new project and add a new folder</a></li>
<li class="chapter" data-level="5.4.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#using-the-console"><i class="fa fa-check"></i><b>5.4.3</b> Using the console</a></li>
<li class="chapter" data-level="5.4.4" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-make-a-data-object-vector-in-r"><i class="fa fa-check"></i><b>5.4.4</b> Action: Make a data object (vector) in R</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#data-abstraction-and-data-visualisation"><i class="fa fa-check"></i><b>5.5</b> Data abstraction and data visualisation</a><ul>
<li class="chapter" data-level="5.5.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-visualise-the-data-using-a-simple-histogram"><i class="fa fa-check"></i><b>5.5.1</b> Action: Visualise the data using a simple histogram</a></li>
<li class="chapter" data-level="5.5.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-close-the-project"><i class="fa fa-check"></i><b>5.5.2</b> Action: Close the project</a></li>
<li class="chapter" data-level="5.5.3" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-restore-the-project"><i class="fa fa-check"></i><b>5.5.3</b> Action: Restore the project</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#working-with-markdown-documents."><i class="fa fa-check"></i><b>5.6</b> Working with markdown documents.</a><ul>
<li class="chapter" data-level="5.6.1" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-produce-a-default-markdown-document."><i class="fa fa-check"></i><b>5.6.1</b> Action: Produce a default markdown document.</a></li>
<li class="chapter" data-level="5.6.2" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#action-clean-out-rinse-and-repeat-for-practice-sake"><i class="fa fa-check"></i><b>5.6.2</b> Action: Clean out, rinse and repeat, for practice sake</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="introduction-to-the-rstudio-server.html"><a href="introduction-to-the-rstudio-server.html#conclusion"><i class="fa fa-check"></i><b>5.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html"><i class="fa fa-check"></i><b>6</b> Basic statistical concepts. Refresher using a simple example</a><ul>
<li class="chapter" data-level="6.0.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#getting-some-data"><i class="fa fa-check"></i><b>6.0.1</b> Getting some data</a></li>
<li class="chapter" data-level="6.0.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-get-some-personal-data"><i class="fa fa-check"></i><b>6.0.2</b> Action: Get some personal data</a></li>
<li class="chapter" data-level="6.0.3" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-summarise-the-class-data"><i class="fa fa-check"></i><b>6.0.3</b> Action: Summarise the class data</a></li>
<li class="chapter" data-level="6.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#inferential-statistics"><i class="fa fa-check"></i><b>6.1</b> Inferential statistics</a><ul>
<li class="chapter" data-level="6.1.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-calculate-the-standard-deviation-by-hand"><i class="fa fa-check"></i><b>6.1.1</b> Action: Calculate the standard deviation “by hand”</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#calcuate-the-standard-error-of-the-mean."><i class="fa fa-check"></i><b>6.2</b> Calcuate the standard error of the mean.</a><ul>
<li class="chapter" data-level="6.2.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-calculate-the-standard-error-and-95-confidence-interval-for-the-mean"><i class="fa fa-check"></i><b>6.2.1</b> Action: Calculate the standard error and 95% confidence interval for the mean</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#test-whether-the-statistics-work"><i class="fa fa-check"></i><b>6.3</b> Test whether the statistics “work”</a><ul>
<li class="chapter" data-level="6.3.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#action-rinse-and-repeat."><i class="fa fa-check"></i><b>6.3.1</b> Action: Rinse and repeat.</a></li>
<li class="chapter" data-level="6.3.2" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#conclusion-1"><i class="fa fa-check"></i><b>6.3.2</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#planning-an-analysis"><i class="fa fa-check"></i><b>6.4</b> Planning an analysis</a><ul>
<li class="chapter" data-level="6.4.1" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#understanding-your-data-before-you-start-colllecting-them"><i class="fa fa-check"></i><b>6.4.1</b> Understanding your data before you start colllecting them</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#quantitative-analysis"><i class="fa fa-check"></i><b>6.5</b> Quantitative analysis</a></li>
<li class="chapter" data-level="6.6" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#what-does-quantitative-data-consist-of"><i class="fa fa-check"></i><b>6.6</b> What does quantitative data consist of?</a></li>
<li class="chapter" data-level="6.7" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#data-visualisation-vs-statistical-analysis"><i class="fa fa-check"></i><b>6.7</b> Data visualisation vs statistical analysis</a></li>
<li class="chapter" data-level="6.8" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#a-simple-example"><i class="fa fa-check"></i><b>6.8</b> A simple example</a></li>
<li class="chapter" data-level="6.9" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#graphical-data-analysis"><i class="fa fa-check"></i><b>6.9</b> Graphical data analysis</a></li>
<li class="chapter" data-level="6.10" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#forming-a-plot-in-r"><i class="fa fa-check"></i><b>6.10</b> Forming a plot in R</a></li>
<li class="chapter" data-level="6.11" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#a-more-complex-time-series"><i class="fa fa-check"></i><b>6.11</b> A more complex time series</a></li>
<li class="chapter" data-level="6.12" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#some-high-level-code-to-break-down-the-data"><i class="fa fa-check"></i><b>6.12</b> Some high level code to break down the data</a></li>
<li class="chapter" data-level="6.13" data-path="basic-statistical-concepts-refresher-using-a-simple-example.html"><a href="basic-statistical-concepts-refresher-using-a-simple-example.html#inferential-statistics-1"><i class="fa fa-check"></i><b>6.13</b> Inferential statistics</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html"><i class="fa fa-check"></i><b>7</b> Confidence intervals for univariate data</a><ul>
<li class="chapter" data-level="7.1" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#introduction-2"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#reminder-basic-statistics"><i class="fa fa-check"></i><b>7.2</b> Reminder: Basic statistics</a></li>
<li class="chapter" data-level="7.3" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.3</b> Measures of central tendency</a><ul>
<li class="chapter" data-level="7.3.1" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#measures-of-variability"><i class="fa fa-check"></i><b>7.3.1</b> Measures of variability</a></li>
<li class="chapter" data-level="7.3.2" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#the-normal-distribution"><i class="fa fa-check"></i><b>7.3.2</b> The normal distribution</a></li>
<li class="chapter" data-level="7.3.3" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#checking-data-properties-with-figures"><i class="fa fa-check"></i><b>7.3.3</b> Checking data properties with figures</a></li>
<li class="chapter" data-level="7.3.4" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#calculating-the-standard-error"><i class="fa fa-check"></i><b>7.3.4</b> Calculating the standard error</a></li>
<li class="chapter" data-level="7.3.5" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#the-sampling-distribution-of-the-mean"><i class="fa fa-check"></i><b>7.3.5</b> The sampling distribution of the mean</a></li>
<li class="chapter" data-level="7.3.6" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#calculating-confidence-intervals"><i class="fa fa-check"></i><b>7.3.6</b> Calculating confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="confidence-intervals-for-univariate-data.html"><a href="confidence-intervals-for-univariate-data.html#conclusion-and-take-home-messages"><i class="fa fa-check"></i><b>7.4</b> Conclusion and take home messages</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html"><i class="fa fa-check"></i><b>8</b> Using figures to understand and present data</a><ul>
<li class="chapter" data-level="8.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#quick-exploratory-plots"><i class="fa fa-check"></i><b>8.1</b> Quick exploratory plots</a></li>
<li class="chapter" data-level="8.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#introduction-to-grammar-of-graphics-plots"><i class="fa fa-check"></i><b>8.2</b> Introduction to grammar of graphics plots</a></li>
<li class="chapter" data-level="8.3" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#simple-bar-charts"><i class="fa fa-check"></i><b>8.3</b> Simple bar charts</a><ul>
<li class="chapter" data-level="8.3.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#exercise-3"><i class="fa fa-check"></i><b>8.3.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#simple-line-charts"><i class="fa fa-check"></i><b>8.4</b> Simple Line charts</a><ul>
<li class="chapter" data-level="8.4.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#exercise-4"><i class="fa fa-check"></i><b>8.4.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#histograms"><i class="fa fa-check"></i><b>8.5</b> Histograms</a><ul>
<li class="chapter" data-level="8.5.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#default-histogram"><i class="fa fa-check"></i><b>8.5.1</b> Default histogram</a></li>
<li class="chapter" data-level="8.5.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#facet-wrapping"><i class="fa fa-check"></i><b>8.5.2</b> Facet wrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#boxplots"><i class="fa fa-check"></i><b>8.6</b> Boxplots</a></li>
<li class="chapter" data-level="8.7" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#confidence-interval-plots"><i class="fa fa-check"></i><b>8.7</b> Confidence interval plots</a><ul>
<li class="chapter" data-level="8.7.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#dynamite-plots-dont-use"><i class="fa fa-check"></i><b>8.7.1</b> Dynamite plots (Don’t use!)</a></li>
<li class="chapter" data-level="8.7.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#inference-on-medians"><i class="fa fa-check"></i><b>8.7.2</b> Inference on medians</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#scatterplots"><i class="fa fa-check"></i><b>8.8</b> Scatterplots</a><ul>
<li class="chapter" data-level="8.8.1" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#adding-a-regression-line"><i class="fa fa-check"></i><b>8.8.1</b> Adding a regression line</a></li>
<li class="chapter" data-level="8.8.2" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#grouping-and-conditioning"><i class="fa fa-check"></i><b>8.8.2</b> Grouping and conditioning</a></li>
<li class="chapter" data-level="8.8.3" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#curvilinear-relationships"><i class="fa fa-check"></i><b>8.8.3</b> Curvilinear relationships</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#generalised-linear-models"><i class="fa fa-check"></i><b>8.9</b> Generalised linear models</a></li>
<li class="chapter" data-level="8.10" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#binomial-data"><i class="fa fa-check"></i><b>8.10</b> Binomial data</a></li>
<li class="chapter" data-level="8.11" data-path="using-figures-to-understand-and-present-data.html"><a href="using-figures-to-understand-and-present-data.html#learning-more-about-ggplots"><i class="fa fa-check"></i><b>8.11</b> Learning more about ggplots</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html"><i class="fa fa-check"></i><b>9</b> T tests and hypothesis testing</a><ul>
<li class="chapter" data-level="9.1" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#statistical-hypothesis-testing"><i class="fa fa-check"></i><b>9.1</b> Statistical hypothesis testing</a><ul>
<li class="chapter" data-level="9.1.1" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#the-unpaired-t-test"><i class="fa fa-check"></i><b>9.1.1</b> The unpaired t-test</a></li>
<li class="chapter" data-level="9.1.2" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#the-t-statistic"><i class="fa fa-check"></i><b>9.1.2</b> The t-statistic</a></li>
<li class="chapter" data-level="9.1.3" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#interpretation-of-a-p-value"><i class="fa fa-check"></i><b>9.1.3</b> Interpretation of a p-value</a></li>
<li class="chapter" data-level="9.1.4" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#tests-and-confidence-intervals"><i class="fa fa-check"></i><b>9.1.4</b> Tests and confidence intervals</a></li>
<li class="chapter" data-level="9.1.5" data-path="t-tests-and-hypothesis-testing.html"><a href="t-tests-and-hypothesis-testing.html#using-hypothesis-tests-wisely"><i class="fa fa-check"></i><b>9.1.5</b> Using hypothesis tests wisely</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html"><i class="fa fa-check"></i><b>10</b> Introduction to one way ANOVA</a><ul>
<li class="chapter" data-level="10.0.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#multiple-comparisons"><i class="fa fa-check"></i><b>10.0.1</b> Multiple comparisons</a></li>
<li class="chapter" data-level="10.0.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#visualising-between-group-variation-using-boxplots"><i class="fa fa-check"></i><b>10.0.2</b> Visualising between group variation using boxplots</a></li>
<li class="chapter" data-level="10.0.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#boxplot-statistics"><i class="fa fa-check"></i><b>10.0.3</b> Boxplot statistics</a></li>
<li class="chapter" data-level="10.0.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#plotting-confidence-intervals-for-each-group"><i class="fa fa-check"></i><b>10.0.4</b> Plotting confidence intervals for each group</a></li>
<li class="chapter" data-level="10.0.5" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#fitting-a-model"><i class="fa fa-check"></i><b>10.0.5</b> Fitting a model</a></li>
<li class="chapter" data-level="10.0.6" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#the-f-ratio-and-degrees-of-freedom"><i class="fa fa-check"></i><b>10.0.6</b> The F ratio and degrees of freedom</a></li>
<li class="chapter" data-level="10.0.7" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>10.0.7</b> Homogeneity of variance</a></li>
<li class="chapter" data-level="10.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#alternative-to-the-one-way-test"><i class="fa fa-check"></i><b>10.1</b> Alternative to the one way test</a><ul>
<li class="chapter" data-level="10.1.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#determining-where-the-differences-lie"><i class="fa fa-check"></i><b>10.1.1</b> Determining where the differences lie</a></li>
<li class="chapter" data-level="10.1.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#bonferoni-corrections"><i class="fa fa-check"></i><b>10.1.2</b> Bonferoni corrections</a></li>
<li class="chapter" data-level="10.1.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#tukeys-honest-significant-difference"><i class="fa fa-check"></i><b>10.1.3</b> Tukey’s honest significant difference</a></li>
<li class="chapter" data-level="10.1.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#the-kruskal-wallace-non-parametric-test."><i class="fa fa-check"></i><b>10.1.4</b> The Kruskal Wallace non parametric test.</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#power-analysis"><i class="fa fa-check"></i><b>10.2</b> Power analysis</a></li>
<li class="chapter" data-level="10.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#exercise-5"><i class="fa fa-check"></i><b>10.3</b> Exercise</a></li>
<li class="chapter" data-level="10.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#references"><i class="fa fa-check"></i><b>10.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html"><i class="fa fa-check"></i><b>11</b> Regression as a statistical modelling</a><ul>
<li class="chapter" data-level="11.0.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#uses-of-models"><i class="fa fa-check"></i><b>11.0.1</b> Uses of models</a></li>
<li class="chapter" data-level="11.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#the-general-linear-model"><i class="fa fa-check"></i><b>11.1</b> The general linear model</a></li>
<li class="chapter" data-level="11.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#regression"><i class="fa fa-check"></i><b>11.2</b> Regression</a><ul>
<li class="chapter" data-level="11.2.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#theory"><i class="fa fa-check"></i><b>11.2.1</b> Theory</a></li>
<li class="chapter" data-level="11.2.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#example"><i class="fa fa-check"></i><b>11.2.2</b> Example</a></li>
<li class="chapter" data-level="11.2.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#confidence-intervals"><i class="fa fa-check"></i><b>11.2.3</b> Confidence intervals</a></li>
<li class="chapter" data-level="11.2.4" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#prediction-1"><i class="fa fa-check"></i><b>11.2.4</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#using-ggplot2-for-confidence-intervals."><i class="fa fa-check"></i><b>11.3</b> Using ggplot2 for confidence intervals.</a><ul>
<li class="chapter" data-level="11.3.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#prediction-intervals"><i class="fa fa-check"></i><b>11.3.1</b> Prediction intervals</a></li>
<li class="chapter" data-level="11.3.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#diagnostics"><i class="fa fa-check"></i><b>11.3.2</b> Diagnostics</a></li>
<li class="chapter" data-level="11.3.3" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#lack-of-independence"><i class="fa fa-check"></i><b>11.3.3</b> Lack of independence</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#where-do-the-sum-of-squares-come-from"><i class="fa fa-check"></i><b>11.4</b> Where do the sum of squares come from?</a><ul>
<li class="chapter" data-level="11.4.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#regression-1"><i class="fa fa-check"></i><b>11.4.1</b> Regression</a></li>
<li class="chapter" data-level="11.4.2" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#residuals"><i class="fa fa-check"></i><b>11.4.2</b> Residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#where-does-r-squared-coefficient-of-determination-come-from"><i class="fa fa-check"></i><b>11.5</b> Where does R squared (coefficient of determination) come from?</a><ul>
<li class="chapter" data-level="11.5.1" data-path="regression-as-a-statistical-modelling.html"><a href="regression-as-a-statistical-modelling.html#violations-of-assumptions"><i class="fa fa-check"></i><b>11.5.1</b> Violations of assumptions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="advice-on-regression.html"><a href="advice-on-regression.html"><i class="fa fa-check"></i><b>12</b> Advice on regression</a><ul>
<li class="chapter" data-level="12.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#introduction-3"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="advice-on-regression.html"><a href="advice-on-regression.html#predictive-modelling-calibration"><i class="fa fa-check"></i><b>12.2</b> Predictive modelling: Calibration</a><ul>
<li class="chapter" data-level="12.2.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up"><i class="fa fa-check"></i><b>12.2.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="advice-on-regression.html"><a href="advice-on-regression.html#explanatory-modelling"><i class="fa fa-check"></i><b>12.3</b> Explanatory modelling:</a><ul>
<li class="chapter" data-level="12.3.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-1"><i class="fa fa-check"></i><b>12.3.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="advice-on-regression.html"><a href="advice-on-regression.html#testing-for-a-relationship"><i class="fa fa-check"></i><b>12.4</b> Testing for a relationship</a><ul>
<li class="chapter" data-level="12.4.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-2"><i class="fa fa-check"></i><b>12.4.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="advice-on-regression.html"><a href="advice-on-regression.html#diagnostics-show-assumptions-not-met"><i class="fa fa-check"></i><b>12.5</b> Diagnostics show assumptions not met</a></li>
<li class="chapter" data-level="12.6" data-path="advice-on-regression.html"><a href="advice-on-regression.html#skewed-independent-variable"><i class="fa fa-check"></i><b>12.6</b> Skewed independent variable</a><ul>
<li class="chapter" data-level="12.6.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-3"><i class="fa fa-check"></i><b>12.6.1</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="advice-on-regression.html"><a href="advice-on-regression.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>12.7</b> Spearman’s rank correlation</a><ul>
<li class="chapter" data-level="12.7.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#taking-ranks"><i class="fa fa-check"></i><b>12.7.1</b> Taking ranks</a></li>
<li class="chapter" data-level="12.7.2" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-4"><i class="fa fa-check"></i><b>12.7.2</b> Advice on writing up</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="advice-on-regression.html"><a href="advice-on-regression.html#non-linear-response"><i class="fa fa-check"></i><b>12.8</b> Non linear response</a><ul>
<li class="chapter" data-level="12.8.1" data-path="advice-on-regression.html"><a href="advice-on-regression.html#advice-on-writing-up-5"><i class="fa fa-check"></i><b>12.8.1</b> Advice on writing up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html"><i class="fa fa-check"></i><b>13</b> Crib sheet for regression and ANOVA</a><ul>
<li class="chapter" data-level="13.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#introduction-4"><i class="fa fa-check"></i><b>13.1</b> Introduction</a><ul>
<li class="chapter" data-level="13.1.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#packages-needed"><i class="fa fa-check"></i><b>13.1.1</b> Packages needed</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#loading-the-data"><i class="fa fa-check"></i><b>13.2</b> Loading the data</a></li>
<li class="chapter" data-level="13.3" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#finding-out-about-the-data"><i class="fa fa-check"></i><b>13.3</b> Finding out about the data</a></li>
<li class="chapter" data-level="13.4" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#making-your-data-available-to-others"><i class="fa fa-check"></i><b>13.4</b> Making your data available to others</a><ul>
<li class="chapter" data-level="13.4.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#note-this-only-works-as-an-html-document"><i class="fa fa-check"></i><b>13.4.1</b> NOTE THIS ONLY WORKS AS AN HTML DOCUMENT</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#subsetting"><i class="fa fa-check"></i><b>13.5</b> Subsetting</a></li>
<li class="chapter" data-level="13.6" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#data-summaries-for-individual-variables"><i class="fa fa-check"></i><b>13.6</b> Data summaries for individual variables</a></li>
<li class="chapter" data-level="13.7" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#individual-statistics-for-a-single-variable"><i class="fa fa-check"></i><b>13.7</b> Individual statistics for a single variable</a></li>
<li class="chapter" data-level="13.8" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#simple-boxplot-of-one-variable"><i class="fa fa-check"></i><b>13.8</b> Simple boxplot of one variable</a></li>
<li class="chapter" data-level="13.9" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#simple-histogram-of-one-variable"><i class="fa fa-check"></i><b>13.9</b> Simple histogram of one variable</a></li>
<li class="chapter" data-level="13.10" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#neater-histogram-of-one-variable"><i class="fa fa-check"></i><b>13.10</b> Neater histogram of one variable</a></li>
<li class="chapter" data-level="13.11" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#regression-2"><i class="fa fa-check"></i><b>13.11</b> Regression</a></li>
<li class="chapter" data-level="13.12" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#scatterplot-without-fitted-line"><i class="fa fa-check"></i><b>13.12</b> Scatterplot without fitted line</a></li>
<li class="chapter" data-level="13.13" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#scatterplot-with-fitted-line-and-labels"><i class="fa fa-check"></i><b>13.13</b> Scatterplot with fitted line and labels</a></li>
<li class="chapter" data-level="13.14" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-a-model-1"><i class="fa fa-check"></i><b>13.14</b> Fitting a model</a></li>
<li class="chapter" data-level="13.15" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#extracting-residuals"><i class="fa fa-check"></i><b>13.15</b> Extracting residuals</a></li>
<li class="chapter" data-level="13.16" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-summary"><i class="fa fa-check"></i><b>13.16</b> Model summary</a></li>
<li class="chapter" data-level="13.17" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-anova-table"><i class="fa fa-check"></i><b>13.17</b> Model anova table</a></li>
<li class="chapter" data-level="13.18" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#confidence-intervals-for-the-model-parameters"><i class="fa fa-check"></i><b>13.18</b> Confidence intervals for the model parameters</a><ul>
<li class="chapter" data-level="13.18.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#model-diagnostics"><i class="fa fa-check"></i><b>13.18.1</b> Model diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="13.19" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#spearmans-rank-correlation-1"><i class="fa fa-check"></i><b>13.19</b> Spearman’s rank correlation</a><ul>
<li class="chapter" data-level="13.19.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-a-spline"><i class="fa fa-check"></i><b>13.19.1</b> Fitting a spline</a></li>
</ul></li>
<li class="chapter" data-level="13.20" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#one-way-anova"><i class="fa fa-check"></i><b>13.20</b> One way ANOVA</a><ul>
<li class="chapter" data-level="13.20.1" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#grouped-boxplots"><i class="fa fa-check"></i><b>13.20.1</b> Grouped boxplots</a></li>
</ul></li>
<li class="chapter" data-level="13.21" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#histograms-for-each-factor-level"><i class="fa fa-check"></i><b>13.21</b> Histograms for each factor level</a></li>
<li class="chapter" data-level="13.22" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#confidence-interval-plot"><i class="fa fa-check"></i><b>13.22</b> Confidence interval plot</a></li>
<li class="chapter" data-level="13.23" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#fitting-anova"><i class="fa fa-check"></i><b>13.23</b> Fitting ANOVA</a></li>
<li class="chapter" data-level="13.24" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#tukey-corrected-pairwise-comparisons"><i class="fa fa-check"></i><b>13.24</b> Tukey corrected pairwise comparisons</a></li>
<li class="chapter" data-level="13.25" data-path="crib-sheet-for-regression-and-anova.html"><a href="crib-sheet-for-regression-and-anova.html#anova-with-whites-correction"><i class="fa fa-check"></i><b>13.25</b> Anova with White’s correction</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html"><i class="fa fa-check"></i><b>14</b> Crib sheet for GIS in R</a><ul>
<li class="chapter" data-level="14.1" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#introduction-5"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-in-a-shapefile"><i class="fa fa-check"></i><b>14.2</b> Reading in a shapefile</a></li>
<li class="chapter" data-level="14.3" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#transforming-to-british-national-grid"><i class="fa fa-check"></i><b>14.3</b> Transforming to British National Grid</a></li>
<li class="chapter" data-level="14.4" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#mapview-of-a-polygon-layer"><i class="fa fa-check"></i><b>14.4</b> Mapview of a polygon layer</a></li>
<li class="chapter" data-level="14.5" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#adding-an-overview-map"><i class="fa fa-check"></i><b>14.5</b> Adding an overview map</a></li>
<li class="chapter" data-level="14.6" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#adding-a-measurement-tool"><i class="fa fa-check"></i><b>14.6</b> Adding a measurement tool</a></li>
<li class="chapter" data-level="14.7" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-in-points-from-a-csv"><i class="fa fa-check"></i><b>14.7</b> Reading in points from a CSV</a></li>
<li class="chapter" data-level="14.8" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#reading-raster-data"><i class="fa fa-check"></i><b>14.8</b> Reading raster data</a></li>
<li class="chapter" data-level="14.9" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#making-colour-ramps-for-raster-data"><i class="fa fa-check"></i><b>14.9</b> Making colour ramps for raster data</a></li>
<li class="chapter" data-level="14.10" data-path="crib-sheet-for-gis-in-r.html"><a href="crib-sheet-for-gis-in-r.html#extracting-raster-values-for-points"><i class="fa fa-check"></i><b>14.10</b> Extracting raster values for points</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="hengistbury.html"><a href="hengistbury.html"><i class="fa fa-check"></i><b>15</b> Hengistbury</a></li>
<li class="chapter" data-level="16" data-path="arne-data-quick-load.html"><a href="arne-data-quick-load.html"><i class="fa fa-check"></i><b>16</b> Arne data quick load</a><ul>
<li class="chapter" data-level="16.1" data-path="arne-data-quick-load.html"><a href="arne-data-quick-load.html#introduction-6"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="arne-2019.html"><a href="arne-2019.html"><i class="fa fa-check"></i><b>17</b> Arne 2019</a><ul>
<li class="chapter" data-level="17.1" data-path="arne-2019.html"><a href="arne-2019.html#loading-the-waypoints"><i class="fa fa-check"></i><b>17.1</b> Loading the waypoints</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><i class="fa fa-check"></i><b>18</b> Regression analysis using measurements on individual pines from the Arne 2019 data</a><ul>
<li class="chapter" data-level="18.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#introduction-7"><i class="fa fa-check"></i><b>18.1</b> Introduction</a><ul>
<li class="chapter" data-level="18.1.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#load-r-libraries"><i class="fa fa-check"></i><b>18.1.1</b> Load R libraries</a></li>
<li class="chapter" data-level="18.1.2" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#load-the-data"><i class="fa fa-check"></i><b>18.1.2</b> Load the data</a></li>
<li class="chapter" data-level="18.1.3" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#looking-at-the-data"><i class="fa fa-check"></i><b>18.1.3</b> Looking at the data</a></li>
<li class="chapter" data-level="18.1.4" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#simple-base-r-figures"><i class="fa fa-check"></i><b>18.1.4</b> Simple base R figures</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#scatterplots-1"><i class="fa fa-check"></i><b>18.2</b> Scatterplots</a></li>
<li class="chapter" data-level="18.3" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#regression-vs-correlation-analysis"><i class="fa fa-check"></i><b>18.3</b> Regression vs correlation analysis</a><ul>
<li class="chapter" data-level="18.3.1" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#spline-and-line-analysis"><i class="fa fa-check"></i><b>18.3.1</b> Spline and line analysis</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#fitting-a-regression"><i class="fa fa-check"></i><b>18.4</b> Fitting a regression</a></li>
<li class="chapter" data-level="18.5" data-path="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html"><a href="regression-analysis-using-measurements-on-individual-pines-from-the-arne-2019-data.html#fitting-a-gam"><i class="fa fa-check"></i><b>18.5</b> Fitting a GAM</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><i class="fa fa-check"></i><b>19</b> Analysing the residuals from regression analysis on individual pines from the Arne 2019 data</a><ul>
<li class="chapter" data-level="19.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#introduction-8"><i class="fa fa-check"></i><b>19.1</b> Introduction</a><ul>
<li class="chapter" data-level="19.1.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#load-r-libraries-1"><i class="fa fa-check"></i><b>19.1.1</b> Load R libraries</a></li>
<li class="chapter" data-level="19.1.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#load-the-data-1"><i class="fa fa-check"></i><b>19.1.2</b> Load the data</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#adding-the-gps-points-to-the-pines"><i class="fa fa-check"></i><b>19.2</b> Adding the GPS points to the pines</a></li>
<li class="chapter" data-level="19.3" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#looking-at-the-residual"><i class="fa fa-check"></i><b>19.3</b> Looking at the residual</a><ul>
<li class="chapter" data-level="19.3.1" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#plotting-the-data-by-site"><i class="fa fa-check"></i><b>19.3.1</b> Plotting the data by site</a></li>
<li class="chapter" data-level="19.3.2" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#obtaining-residuals"><i class="fa fa-check"></i><b>19.3.2</b> Obtaining residuals</a></li>
<li class="chapter" data-level="19.3.3" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#plotting-the-residuals-by-site"><i class="fa fa-check"></i><b>19.3.3</b> Plotting the residuals by site</a></li>
<li class="chapter" data-level="19.3.4" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#confidence-intervals-1"><i class="fa fa-check"></i><b>19.3.4</b> Confidence intervals</a></li>
<li class="chapter" data-level="19.3.5" data-path="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html"><a href="analysing-the-residuals-from-regression-analysis-on-individual-pines-from-the-arne-2019-data.html#simple-unpaired-t-test"><i class="fa fa-check"></i><b>19.3.5</b> Simple unpaired t-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html"><i class="fa fa-check"></i><b>20</b> Mapping and analysing pine densities at Arne</a><ul>
<li class="chapter" data-level="20.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#introduction-9"><i class="fa fa-check"></i><b>20.1</b> Introduction</a><ul>
<li class="chapter" data-level="20.1.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#loading-libraries"><i class="fa fa-check"></i><b>20.1.1</b> Loading libraries</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#loading-the-data-1"><i class="fa fa-check"></i><b>20.2</b> Loading the data</a><ul>
<li class="chapter" data-level="20.2.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#points-to-notice"><i class="fa fa-check"></i><b>20.2.1</b> Points to notice</a></li>
<li class="chapter" data-level="20.2.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#making-a-spatial-object-in-r"><i class="fa fa-check"></i><b>20.2.2</b> Making a spatial object in R</a></li>
<li class="chapter" data-level="20.2.3" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action"><i class="fa fa-check"></i><b>20.2.3</b> Action</a></li>
<li class="chapter" data-level="20.2.4" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#comparing-density-in-the-heathland-and-restoration-site."><i class="fa fa-check"></i><b>20.2.4</b> Comparing density in the heathland and restoration site.</a></li>
<li class="chapter" data-level="20.2.5" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#question-how-does-the-pine-density-differ-between-the-heathland-and-the-restoration-site"><i class="fa fa-check"></i><b>20.2.5</b> Question: How does the pine density differ between the heathland and the restoration site?</a></li>
<li class="chapter" data-level="20.2.6" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#boxplot-of-pine-density"><i class="fa fa-check"></i><b>20.2.6</b> Boxplot of pine density</a></li>
<li class="chapter" data-level="20.2.7" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-1"><i class="fa fa-check"></i><b>20.2.7</b> Action</a></li>
<li class="chapter" data-level="20.2.8" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#inferential-confidence-interval-plot"><i class="fa fa-check"></i><b>20.2.8</b> Inferential confidence interval plot</a></li>
<li class="chapter" data-level="20.2.9" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-2"><i class="fa fa-check"></i><b>20.2.9</b> Action</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#section"><i class="fa fa-check"></i><b>20.3</b> ——————————————————-</a></li>
<li class="chapter" data-level="20.4" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#investigating-factors-affecting-pine-densities-on-the-heathland-site"><i class="fa fa-check"></i><b>20.4</b> Investigating factors affecting pine densities on the heathland site</a></li>
<li class="chapter" data-level="20.5" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#spatial-data"><i class="fa fa-check"></i><b>20.5</b> Spatial data</a><ul>
<li class="chapter" data-level="20.5.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#cropping"><i class="fa fa-check"></i><b>20.5.1</b> Cropping</a></li>
<li class="chapter" data-level="20.5.2" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#terrain-analysis-1"><i class="fa fa-check"></i><b>20.5.2</b> Terrain analysis</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#raster-algebra"><i class="fa fa-check"></i><b>20.6</b> Raster algebra</a></li>
<li class="chapter" data-level="20.7" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#raster-aggregation"><i class="fa fa-check"></i><b>20.7</b> Raster aggregation</a><ul>
<li class="chapter" data-level="20.7.1" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#action-3"><i class="fa fa-check"></i><b>20.7.1</b> Action</a></li>
</ul></li>
<li class="chapter" data-level="20.8" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#adding-the-values-to-the-quadrats"><i class="fa fa-check"></i><b>20.8</b> Adding the values to the quadrats</a></li>
<li class="chapter" data-level="20.9" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#distances-to-trees"><i class="fa fa-check"></i><b>20.9</b> Distances to trees</a></li>
<li class="chapter" data-level="20.10" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#data-table"><i class="fa fa-check"></i><b>20.10</b> Data table</a></li>
<li class="chapter" data-level="20.11" data-path="mapping-and-analysing-pine-densities-at-arne.html"><a href="mapping-and-analysing-pine-densities-at-arne.html#writing-out-the-data"><i class="fa fa-check"></i><b>20.11</b> Writing out the data</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html"><i class="fa fa-check"></i><b>21</b> Statistical analysis of the pine density data</a><ul>
<li class="chapter" data-level="21.1" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#introduction-10"><i class="fa fa-check"></i><b>21.1</b> Introduction</a><ul>
<li class="chapter" data-level="21.1.1" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#loading-libraries-1"><i class="fa fa-check"></i><b>21.1.1</b> Loading libraries</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="statistical-analysis-of-the-pine-density-data.html"><a href="statistical-analysis-of-the-pine-density-data.html#running-analyses"><i class="fa fa-check"></i><b>21.2</b> Running analyses</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative and spatial analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-as-a-statistical-modelling" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Regression as a statistical modelling</h1>
<p>One way anova is based on an underlying statistical model. Statistical modelling can allow you to extract more information from your data than some simpler “test” based methods that you may have learned previously. Most contemporary papers in ecology use models of some kind. Even if the nature of the data you collect limits your options, it is very important to learn to fit and interpret statistical models in order to follow the literature.</p>
<div id="what-is-a-statistical-model" class="section level4">
<h4><span class="header-section-number">11.0.0.1</span> What is a statistical model?</h4>
<p>To some extent statistical modelling is easier than other forms of ecological modelling. Building process based models requires a great deal of understanding of a system. Statistical models are built from the data themselves. Providing you do have some data to work with you can let the combination of data and prebuilt algorithms find a model. However there are many issues that make statistical modelling challenging.</p>
<p>A statistical model is a formal mathematical representation of the “sample space”“, in other words the population from which measurements could have been drawn. It has two components.</p>
<ul>
<li><p>An underlying “deterministic”&quot; component, that usually represents a process of interest</p></li>
<li><p>A stochastic component representing “unexplained” variability So, a statistical model effectively partitions variability into two parts. One part represents some form of potentially interesting relationship between variables. The other part is just “random noise”. Because statistics is all about variability, the “noise” component is actually very important. The variability must be looked at in detail on order to decide on the right model. Many of the challenges involved in choosing between statistical models involves finding a way to “explain” the “unexplained” variability. This fundamental contradiction is why statistical concepts are so hard to understand.</p></li>
</ul>
</div>
<div id="uses-of-models" class="section level3">
<h3><span class="header-section-number">11.0.1</span> Uses of models</h3>
<p>The literature on statistical modelling frequently uses the terms “explanation”&quot; and “prediction”&quot; to describe the way models are used. Although the same model can have both roles, it is worth thinking about the difference between them before fitting and interpreting any models.</p>
<div id="prediction" class="section level4">
<h4><span class="header-section-number">11.0.1.1</span> Prediction</h4>
<p>Models can be used to predict the values for some variable when we are given information regarding some other variable upon which it depends. An example is a calibration curve used in chemistry. We know that conductivity and salinity are directly related. So if we measure the conductivity of liquids with known salinities we can fit a line. We can then use the resulting model to predict salinity at any point between the two extremes that we used when finding the calibration curve. Notice that we cannot easily extrapolate beyond the range of data we have. We will see how the same concept applies to the models we use in quantiative ecology.</p>
<p>Predictions are more reliable if a large portion of the variability in the data can be “explained” through relationships with other variables. The more random variability in the data, the more difficult prediction becomes.</p>
</div>
<div id="explanation" class="section level4">
<h4><span class="header-section-number">11.0.1.2</span> Explanation</h4>
<p>The idea that the variability in the data can be “explained” by some variable comes from the terminology that was used when interpretating experimental data. Experiments usually involve a manipulation and a control of some description. If values for some response differ between control and intervention then it is reasonable to assume that the difference is “explained” by the intervention. If you wish to obtain data that are simple to analyse and interpret you should always design an experiment. However, experiments can be costly. Ecological systems are often slow to respond to interventions, making experiments impossible within the time scale of a master’s dissertation. We are often interested in systems that cannot be easily modified anyway on ethical or practical grounds. Thus in ecology we often have to interpret associations between variables as evidence of process that “explain” a relationship. <strong>Correlation is not causation.</strong> Although patterns of association can provide insight into causality they are not enough to establish it. So, when you read the words “variance explained” look carefully at the sort of data that are being analysed. In an ecological setting this may only suggest close association between variables, not a true explanation in the everyday sense of the word.</p>
<p>When there is a great deal of variability in the data we may want to ask whether any of the variability at all is “explained” by other variables. This is where statistical tests and p-values have a purpose. When faced with small amounts of noisy data it can be useful simply to ask whether more variability is associated with some variable than would occur by chance.</p>
</div>
</div>
<div id="the-general-linear-model" class="section level2">
<h2><span class="header-section-number">11.1</span> The general linear model</h2>
<p>General linear models lie behind a large number of techniques. These have different names depending on the type of data used to explain or predict the variability in a numerical response variable.</p>
<ul>
<li>Regression (Numerical variable)</li>
<li>Analysis of variance (One or more categorical variables)</li>
<li>Analysis of covariance (Categorical variable plus numerical variable)</li>
<li>Multiple regression (Multiple numerical variables)</li>
</ul>
<p>Although these analyses are given different names and they appear in different parts of the menu in a program such as SPSS, they are all based on a similar mathematical approach to model fitting. In R the same model syntax is used in all cases. The steps needed to build any linear model are…</p>
<ul>
<li>Look at the data carefully without fitting any model. Try different ways of plotting the data. Look for patterns in the data that suggest that they are suitable for modelling.</li>
<li>Fit a model: The standard R syntax for a simple linear regression model is <strong>mod&lt;-lm(y~x)</strong> However model formulae may be much more complex.</li>
<li>Look at whether the terms that have been entered in the model are significant: The simplest R syntax is <strong>anova(mod)</strong>. Again, this part of the process can be become much more involved in the case of models with many terms.</li>
<li>Summarise the model in order to understand the structure of the model. This can be achieved with <strong>summary(mod)</strong></li>
<li>Run diagnostics to check that assumptions are adequately met. This involves a range of techniques including statistical tests and graphical diagnoses. This step is extremely important and must be addressed carefully in order to ensure that the results of the exercise are reliable.</li>
</ul>
</div>
<div id="regression" class="section level2">
<h2><span class="header-section-number">11.2</span> Regression</h2>
<div id="theory" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Theory</h3>
<p>The regression equation is ..</p>
<p><span class="math inline">\(y=a+bx+\epsilon\)</span> where <span class="math inline">\(\epsilon=N(o,\sigma^{2})\)</span></p>
<p>In other words it is a straight line with a as the intercept, b as the slope, with the assumption of normally distributed errors (variability around the line)</p>
<p>The diagram below taken from Zuur et al (2007) illustrates the basic idea. In theory, if we had an infinite number of observations around each point in a fitted model, the variability would form a perfect normal distribution. The shape and width of the normal curves would be constant along the length of the model. These normal curves form the stochastic part of the model. The strait line is the deterministic part. This represents the relationship we are usually most interested in. The line is defines by its intercept with the axis and its slope.</p>
<div class="figure">
<img src="images/figs/regression1.png" />

</div>
<p>For any observed value of y there will be a fitted value (or predicted value) that falls along the line. The difference between the fitted value and the observed value is known as the residual.</p>
<div class="figure">
<img src="images/figs/regression.png" />

</div>
<p>In reality we do not have infinite observed values at each point. However if we collected all the residuals together we should get a normal distribution.</p>
</div>
<div id="example" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Example</h3>
<p>The example is taken from Crawley’s R book. It is very simplified and idealised, but serves to explain the concepts. Crawley’s own ecological research involves herbivory. Here he presents an example in which the growth of insect larvae on leaves with different concentrations of tannin has been measured. Tannin concentrations slow insect growth (Crawley unfortunately does not provide the units in which this is measured). The question is, how much is growth inhibited by an increase of 1% in tannin concentration? The first step after loading the data is to produce a scatterplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">larvae&lt;-<span class="kw">read.csv</span>(<span class="st">&quot;/home/msc_scripts/data/larvae.csv&quot;</span>)
<span class="kw">names</span>(larvae)</code></pre></div>
<pre><code>## [1] &quot;growth&quot; &quot;tannin&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(larvae)
<span class="kw">plot</span>(growth<span class="op">~</span>tannin)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-138-1.png" width="672" /></p>
<p>The scatterplot is produced using the syntax that we will use in the model. Growth is a function of (~) tannin.</p>
<p>We now fit a model and assign the results to an object in R. We can call this “mod”. This contains all the information about the fitted model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(growth<span class="op">~</span>tannin)</code></pre></div>
<p>We can now look at the properties of the model. If we ask for an “anova”. R will produce the following output.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(mod)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: growth
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## tannin     1 88.817  88.817  30.974 0.0008461 ***
## Residuals  7 20.072   2.867                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This is similar to the table produced for an ANOVA involving categegorical variables (factors). It can be interpreted in a similar way. Just as for an ANOVA we have an F ratio that represents the amount of variability that falls along the regression line divided by the residual variation.</p>
<p>The numerator degrees of freedom for a simple regression is always one. The numerator degrees of freedom is n-2 as we have estimated two parameters, the slope and the intercept. Thus we have found a very significant effect of tannin concentration on growth F(1, 7) =31, p &lt;0.001. You should report the R² values along with the p-value.</p>
<p>A correlation test would have shown the same significant relationship, but without as much detail.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(growth,tannin)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  growth and tannin
## t = -5.5654, df = 7, p-value = 0.0008461
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.9796643 -0.5972422
## sample estimates:
##        cor 
## -0.9031408</code></pre>
<p>The additional information that we have with a regression concerns the two elements in the regression equation. The slope and the intercept.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mod)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = growth ~ tannin)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4556 -0.8889 -0.2389  0.9778  2.8944 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.7556     1.0408  11.295 9.54e-06 ***
## tannin       -1.2167     0.2186  -5.565 0.000846 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.693 on 7 degrees of freedom
## Multiple R-squared:  0.8157, Adjusted R-squared:  0.7893 
## F-statistic: 30.97 on 1 and 7 DF,  p-value: 0.0008461</code></pre>
<p>Remember the equation we used.</p>
<p><span class="math inline">\(y=a+bx+\epsilon\)</span></p>
<p>The intercept (a) is 11.76</p>
<p>The slope (b) is -1.22</p>
<p>Which means that growth (whatever this was measured in by Crawley) is reduced by 1.22 for each increase of 1% in tannin concentration.</p>
</div>
<div id="confidence-intervals" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Confidence intervals</h3>
<p>There is an issue with this way of summarising the results. If we only report the coefficients as given we have ignored the fact that there was unexplained variation in the model. This variation produces uncertainty regarding the true values of the parameters. The greater the unexplained variation (scatter or noise) around the line, the less confident we can be regarding their values. The statistical mechanism used in the calculations (that is not particularly complex, but can safely be taken on trust) allows us find confidence intervals for the parameters. If the confidence intervals do not include zero then the parameters are significant. There are only a few cases where this is very meaningful for the intercept. We are usually more interested in the slope.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(mod)</code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept)  9.294457 14.2166544
## tannin      -1.733601 -0.6997325</code></pre>
<p>So now we can go a bit further. Instead of giving a point estimate for the effect of tannin on growth we can state that the 95% confidence interval for the effect of a 1% increase of tannin on growth lies between -1.73 and -0.7</p>
</div>
<div id="prediction-1" class="section level3">
<h3><span class="header-section-number">11.2.4</span> Prediction</h3>
<p>The equation can be used to predict the most likely value of y given a value of x. If we just ask R to “predict” we get the fitted values for the values of the explanatory variable that we used when fitting the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(mod)</code></pre></div>
<pre><code>##         1         2         3         4         5         6         7 
## 11.755556 10.538889  9.322222  8.105556  6.888889  5.672222  4.455556 
##         8         9 
##  3.238889  2.022222</code></pre>
<p>So we can plot out the data again and show the predicted values as red points and draw the regression line.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(growth<span class="op">~</span>tannin)
<span class="kw">points</span>(tannin,<span class="kw">predict</span>(mod),<span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">bg=</span><span class="dv">2</span>)
<span class="kw">lines</span>(tannin,<span class="kw">predict</span>(mod))</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-145-1.png" width="672" /></p>
<div id="prediction-with-confidence-intervals" class="section level4">
<h4><span class="header-section-number">11.2.4.1</span> Prediction with confidence intervals</h4>
<p>As we have seen, a statistical model takes into account uncertainty that arises as a result of variability in the data. So we should not simple look at the line of best fit as summing up a regression. We should add some indication of our confidence in the result to the figure.</p>
<p>To achieve this nicely in R requires a couple of extra steps. After plotting the data with plot(growth~tannin) we set up a sequence of 100 x values that lie between the minimum and the maximum. Now if we pass these to the predict function in R and ask for confidence intervals (that by default are 95%) we get the figure below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(growth<span class="op">~</span>tannin)
x&lt;-<span class="kw">seq</span>(<span class="kw">min</span>(tannin),<span class="kw">max</span>(tannin),<span class="dt">length=</span><span class="dv">100</span>) 
<span class="kw">matlines</span>(x,<span class="kw">predict</span>(mod,<span class="kw">list</span>(<span class="dt">tannin=</span>x),<span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>))</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<p>The confidence bands refer to the fitted model. They show uncertainty regarding the regression line and are calculated from the standard error.</p>
</div>
</div>
</div>
<div id="using-ggplot2-for-confidence-intervals." class="section level2">
<h2><span class="header-section-number">11.3</span> Using ggplot2 for confidence intervals.</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
g0&lt;-<span class="kw">ggplot</span>(<span class="dt">data=</span>larvae, <span class="kw">aes</span>(<span class="dt">x=</span>tannin,<span class="dt">y=</span>growth))
g1&lt;-g0<span class="op">+</span><span class="kw">geom_point</span>()
g1<span class="op">+</span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-147-1.png" width="672" /></p>
<div id="prediction-intervals" class="section level3">
<h3><span class="header-section-number">11.3.1</span> Prediction intervals</h3>
<p>There is another way to look at uncertainty. If we know the value for tannin, where would we expect a single measured value for growth to lie. Notice that this is different. The confidence bands show where the mean value migh lie if we measured growth many times. But in this case we want to know where we might expect a data point to fall. This is a much broader interval, and is based on the idea of theoretical normal curves falling around the regression line with a standard deviation estimated from the data. We cut off the tails of these curves.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(growth<span class="op">~</span>tannin)
x&lt;-<span class="kw">seq</span>(<span class="kw">min</span>(tannin),<span class="kw">max</span>(tannin),<span class="dt">length=</span><span class="dv">1000</span>) 
<span class="kw">matlines</span>(x,<span class="kw">predict</span>(mod,<span class="kw">list</span>(<span class="dt">tannin=</span>x),<span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>))</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-148-1.png" width="672" /></p>
</div>
<div id="diagnostics" class="section level3">
<h3><span class="header-section-number">11.3.2</span> Diagnostics</h3>
<p>It is not enough to simply fit a regression line, or any other model. We have to justify our choice of model and convince those who might use it that the assumptions have been adequately met. The question of how close the data are to meeting the assumptions requires model diagnostics.</p>
<p>The basic assumptions for regression</p>
<ul>
<li>Normally distributed errors</li>
<li>Identically distributed errors over the range (homogeneity of variance)</li>
<li>No undue influence of points with high leverage</li>
<li>An underlying linear relationship</li>
<li>Independent errors</li>
</ul>
<p>In this rather artificial example all the assumptions are met. However real ecological data is rarely as simple as this. In order to justify the use of a regression model you must be able to show that the assumptions are not <em>seriously</em> violated. We will come on to what “seriously”&quot; means later.</p>
<div id="normality" class="section level4">
<h4><span class="header-section-number">11.3.2.1</span> Normality</h4>
<p>It is important to remember that the assumption of normality applies to the residuals after a model has been fitted. You do <em>not</em> test the for normality of the variable itself, as the relationship that you are modelling influences the distribution of the variable. You can look at the distribution of the residuals by plotting a histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(<span class="kw">residuals</span>(mod),<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
<p>This looks good enough. A slightly more sophisticated way of spotting deviations from normality is to use a qqplot.</p>
<p>If we ask R to plot a fitted model, we actually get a set of diagnostic plots. There are six of these. By default R will produce four of them. The qqplot is the second in the series. It is used as a visual check of the normality assumption. If the assumption is met the points should fall approximately along the predicted straight line.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mod,<span class="dt">which=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-150-1.png" width="672" /></p>
<p>Qqplots often have a sigmoid shape. This occurs when some of the extreme values fall further along the tail of the normal distribution than expected. Providing this effect is slight it is not a problem. However deviations from the line away from the extremes does show a major departure from the assumption. Interpretation of QQplots requires some experience, but they can be very useful.</p>
<p>If you have doubts about your ability to interpret the plot you could try using a statistical test of normality.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(<span class="kw">residuals</span>(mod))</code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(mod)
## W = 0.98794, p-value = 0.9926</code></pre>
<p>The problem with this test is that it becomes more sensitive as the number of observations increase. Thus you are more likely to get a p-value below 0.05 if you have a lot of data. However violations of normality become much less serious as the number of observations increase. So it can be safe to ignore a significant test result if the QQplot and histogram do not suggest major problems providing you have more than around 30 observations. If the histogram shows clear skew then you should think about a data transform, weighted regression or using a generalised linear model. More about this later.</p>
</div>
<div id="homogeneity-of-variance-1" class="section level4">
<h4><span class="header-section-number">11.3.2.2</span> Homogeneity of variance</h4>
<p>The assumption here is that the distance a point is likely to fall from the fitted line does not change along the x values. This is very often violated. For example if the values represent counts of individuals it is constrained to not fall below zero and will tend to be some function of the expected value. This results in residuals that follow a poisson distribution or more likely, a negative binomial. The characteristic of both these distributions is that the scatter increases as the expected value increases.</p>
<p>The following lines produce some data with this characteristic in order to illustrate the pattern.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">5</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)
x&lt;-<span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>,<span class="dv">20</span>,<span class="dt">rep=</span>T)
y&lt;-<span class="kw">rnegbin</span>(<span class="dv">20</span>,<span class="dt">mu=</span>x,<span class="dt">theta=</span><span class="dv">2</span>)
<span class="kw">plot</span>(y<span class="op">~</span>x)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-153-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod.negbin&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x)</code></pre></div>
<p>You should be able to spot a “fan” effect.</p>
<p>The third diagnostic plot in the series is used to see this effect more clearly. This plot shows the square root of the standardised residuals plotted against the fitted values. Because the square root is used all the values are positive. If there is an increasing (or decreasing) trend in the absolute size of the residuals it should show up on the plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mod.negbin,<span class="dt">which=</span><span class="dv">3</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p>The red line is meant to guide the eye, but you should look carefully at the pattern rather than the line itself.</p>
<p>This is the pattern for the original model, that does not have a problem with heterogeneity of variance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mod,<span class="dt">which=</span><span class="dv">3</span>,<span class="dt">main=</span><span class="st">&quot;Growth model&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
<p>If you are having difficulty interpreting the results you could try a test for the significance of the trend using a correlation test between the variables shown on the diagonistic plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(<span class="kw">sqrt</span>(<span class="kw">stdres</span>(mod.negbin)),<span class="kw">predict</span>(mod.negbin))</code></pre></div>
<pre><code>## Warning in sqrt(stdres(mod.negbin)): NaNs produced</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sqrt(stdres(mod.negbin)) and predict(mod.negbin)
## t = 4.8093, df = 7, p-value = 0.001945
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5071470 0.9737071
## sample estimates:
##       cor 
## 0.8761687</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(<span class="kw">sqrt</span>(<span class="kw">stdres</span>(mod)),<span class="kw">predict</span>(mod))</code></pre></div>
<pre><code>## Warning in sqrt(stdres(mod)): NaNs produced</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sqrt(stdres(mod)) and predict(mod)
## t = -0.50019, df = 2, p-value = 0.6666
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.9803574  0.9236405
## sample estimates:
##        cor 
## -0.3334484</code></pre>
<p>The same sort of caveats apply to the literal interpretation of this test as a decision rule as the normality test. Although most violations of homogeneity of variance have to be taken seriously, large data sets may show statistically significant, but inconsequential violations.</p>
</div>
<div id="leverage" class="section level4">
<h4><span class="header-section-number">11.3.2.3</span> Leverage</h4>
<p>In the artificial example provided by Crawley all the points are equally spaced along the x axis. This is the “classic” form for a regression and prevents problems with leverage. However in ecology we often have to analyse data that does not have this property. Some of the x values on a scatterplot may fall a long way from the centre of the distribution. Such points potentially could have an excessive influence on the form of the fitted model.</p>
<p>The influence a point has on the regression is a function of leverage and distance from a line fitted using all the other points.</p>
<div class="figure">
<img src="/home/msc_scripts/figs/leverage.png" alt="alt text" />
<p class="caption">alt text</p>
</div>
<p>To illustrate this let’s add a point to the data at a high tannin density and assume that zero growth was measured at this value. How much does this new point influence the model?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tannin&lt;-<span class="kw">c</span>(tannin,<span class="dv">15</span>)
growth&lt;-<span class="kw">c</span>(growth,<span class="dv">0</span>)</code></pre></div>
<p>We can plot the new data and show the effect of this one point on the regression line. It is shown in red.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">new.mod&lt;-<span class="kw">lm</span>(growth<span class="op">~</span>tannin)
<span class="kw">plot</span>(growth<span class="op">~</span>tannin)
<span class="kw">lines</span>(tannin,<span class="kw">predict</span>(mod,<span class="kw">list</span>(tannin)))
<span class="kw">lines</span>(tannin,<span class="kw">predict</span>(new.mod,<span class="kw">list</span>(tannin)),<span class="dt">col=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-158-1.png" width="672" /></p>
<p>This data point has shifted the regression quite a lot due to a combination of its distance from the others (which gives it high leverage) and the fact that it lies a long way from the fitted line (high residual deviation). These two effects are captured by a quantity known as Cook’s distance.</p>
<p>The diagnostic plot shows leverage on the x axis and standardised residuals on the y axis. Large residuals with low leverage do not affect the model, so the safe area with low values for Cook’s distance (below 1) forms a funnel shape. Points falling outside this “safe area” can be flagged up.</p>
<p>There are no problem points in the original model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mod,<span class="dt">which=</span><span class="dv">5</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-159-1.png" width="672" /></p>
<p>However the point that we added with both a high leverage and a high deviation from the original model shows up clearly when we diagnose the model with this point included.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(new.mod,<span class="dt">which=</span><span class="dv">5</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
<p>Another way of spotting this influential points is by looking at Cook’s distance directly. Values over 1 are typically considered to be extreme.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(new.mod,<span class="dt">which=</span><span class="dv">4</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-161-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">larvae<span class="op">$</span>cooks&lt;-<span class="kw">cooks.distance</span>(mod)
g0&lt;-<span class="kw">ggplot</span>(<span class="dt">data=</span>larvae, <span class="kw">aes</span>(<span class="dt">x=</span>tannin,<span class="dt">y=</span>growth))
g1&lt;-g0<span class="op">+</span><span class="kw">geom_point</span>()
g1&lt;-g1<span class="op">+</span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)
g1<span class="op">+</span><span class="kw">geom_point</span>(<span class="dt">size=</span>larvae<span class="op">$</span>cooks<span class="op">*</span><span class="dv">10</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-162-1.png" width="672" /></p>
</div>
</div>
<div id="lack-of-independence" class="section level3">
<h3><span class="header-section-number">11.3.3</span> Lack of independence</h3>
<p>The value and sign of the residual deviation should not be related in any way to that of the previous point. If residual values form “clusters” on one side of the line or another it is a sign of lack of independence. There are two causes of this. The most serious is intrinsic temporal or spatial autocorrelation. This is discussed in the next section. A less serious matter is that the shape of the model is not appropriate for the data. We can see this in the last example. While the strait line might have been OK for the range of data originally given by Crawley, a straight line is a poor model when an additional data point is added at a high tannin level. At some point tannin stops all growth, so the underlying model must be asymptotic. Thus the model with the extra point has correlation in the raw residuals. High tannin values have positive residual deviation as a result of the poor fit of the model. This can be seen by using the first diagnostic plot that R produces.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(new.mod, <span class="dt">which=</span><span class="dv">1</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-163-1.png" width="672" /></p>
<p>A common way of testing for lack of independence is the Durbin Watson test for serial autocorrelation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lmtest)</code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dwtest</span>(growth<span class="op">~</span>tannin)</code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  growth ~ tannin
## DW = 2.0168, p-value = 0.3679
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<div id="putting-it-all-together" class="section level4">
<h4><span class="header-section-number">11.3.3.1</span> Putting it all together</h4>
<p>If you just ask R to plot a model you get all four plots. With some practice these should help you spot problems that need attention. Notice that to get four plots on one page you use <strong>par(mfcol=c(2,2))</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfcol=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(mod)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-165-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="where-do-the-sum-of-squares-come-from" class="section level2">
<h2><span class="header-section-number">11.4</span> Where do the sum of squares come from?</h2>
<p>Contemporary approaches to analysis of variance and regression place the two techniques together under the heading of General Linear Models.This is the approach used in R. In both cases the formula that is dropped in to the call to fit a linear model is similar. The difference is that one way ANOVA uses a factor to predict fitted values and calculate residuals whereas regression uses a numerical variable.</p>
<p>In order to demonstrate the fundamental similarity between the two models we will set up some simulated data and then calculate the sum of squares from first principles.</p>
<div id="anova" class="section level4">
<h4><span class="header-section-number">11.4.0.1</span> ANOVA</h4>
<p>Let’s make up a predictor variable. This is a factor with three levels, call them A, B and C. Now, let’s assume that the fitted values (in other words thede terministic pattern of response to the three levels of this factor) are mean values of 10, 15 and 20. These are the expected responses if there were no variability apart from that between groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1</span>)
predictor&lt;-<span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>),<span class="dt">each=</span><span class="dv">10</span>))
fitted&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">12</span>,<span class="dv">20</span>),<span class="dt">each=</span><span class="dv">10</span>)</code></pre></div>
<p>Of course, there is going to be variability within each group. So let’s add this in. We will assume that the variability can be modelled as a normal distribution with mean zero and standard deviation of 5.</p>
<p>So the results we actually get are derived by adding these two components together.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">residuals&lt;-<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean=</span><span class="dv">0</span>,<span class="dt">sd=</span><span class="dv">5</span>)
results&lt;-fitted<span class="op">+</span>residuals
d&lt;-<span class="kw">data.frame</span>(predictor,results)
<span class="kw">boxplot</span>(results<span class="op">~</span>predictor,<span class="dt">data=</span>d)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
<p>Of course, because this was a simulation experiment the actual means will be slightly different to the invested values. We can set up a data frame with true fitted and residual values like this.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(results<span class="op">~</span>predictor,<span class="dt">data=</span>d)
d&lt;-<span class="kw">data.frame</span>(predictor,results,<span class="dt">fitted=</span><span class="kw">fitted</span>(mod),<span class="dt">residuals=</span><span class="kw">residuals</span>(mod))
<span class="kw">head</span>(d)</code></pre></div>
<pre><code>##   predictor   results   fitted  residuals
## 1         A  6.867731 10.66101 -3.7932830
## 2         A 10.918217 10.66101  0.2572027
## 3         A  5.821857 10.66101 -4.8391570
## 4         A 17.976404 10.66101  7.3153901
## 5         A 11.647539 10.66101  0.9865250
## 6         A  5.897658 10.66101 -4.7633558</code></pre>
</div>
<div id="the-numerator-sum-of-squares" class="section level4">
<h4><span class="header-section-number">11.4.0.2</span> The numerator sum of squares</h4>
<p>OK, so where do the numbers in the Anova table come from? The first step is to understand that the numerator sum of squares represents all the deterministic variability in the system. This is the variability attributable to differences between groups. The sum of squares is the sum of the squared deviations around the mean. But, which mean? In this case it is the overall mean value for the respnse.</p>
<p>So, look at the boxplot again, but this time remove the variability and just plot the means. We can show the difference for each mean from the grand mean using arrows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(fitted<span class="op">~</span>predictor,<span class="dt">data=</span>d)
<span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">mean</span>(results),<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="dv">2</span>)
<span class="kw">arrows</span>(<span class="dv">1</span>,<span class="fl">10.66</span>,<span class="dv">1</span>,<span class="kw">mean</span>(results),<span class="dt">code=</span><span class="dv">3</span>)
<span class="kw">arrows</span>(<span class="dv">2</span>,<span class="fl">13.24</span>,<span class="dv">2</span>,<span class="kw">mean</span>(results),<span class="dt">code=</span><span class="dv">3</span>)
<span class="kw">arrows</span>(<span class="dv">3</span>,<span class="fl">19.33</span>,<span class="dv">3</span>,<span class="kw">mean</span>(results),<span class="dt">code=</span><span class="dv">3</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<p>OK, so for each mean there are 10 fitted values. The sum of squares is simply</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nsqrs&lt;-(d<span class="op">$</span>fitted<span class="op">-</span><span class="kw">mean</span>(results))<span class="op">^</span><span class="dv">2</span>
nsumsqrs&lt;-<span class="kw">sum</span>(nsqrs)</code></pre></div>
</div>
<div id="denominator-sum-of-squares" class="section level4">
<h4><span class="header-section-number">11.4.0.3</span> Denominator sum of squares</h4>
<p>The denominator sum of squares in an Anova table represents all the variability that can be attributed to the stochastic component of the model. In other words, the residual variablity. We produced that when simulating the data. The values are simply the residuals once the means for each group have been subtracted.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">g0&lt;-<span class="kw">ggplot</span>(d,<span class="kw">aes</span>(<span class="dt">x=</span>predictor,<span class="dt">y=</span>results))
g0<span class="op">+</span><span class="kw">geom_point</span>(<span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">bg=</span><span class="dv">2</span>)<span class="op">+</span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean,<span class="dt">geom=</span><span class="st">&quot;point&quot;</span>,<span class="dt">size=</span><span class="dv">4</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-171-1.png" width="672" /></p>
<p>So each residual is the distance between the red points and the large black point representing the mean for that group.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dsqrs&lt;-d<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>
dsumsqrs&lt;-<span class="kw">sum</span>(dsqrs)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(results<span class="op">~</span>predictor)
<span class="kw">anova</span>(mod)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: results
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## predictor  2 396.36  198.18  8.9192 0.001062 **
## Residuals 27 599.93   22.22                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nsumsqrs</code></pre></div>
<pre><code>## [1] 396.3639</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dsumsqrs</code></pre></div>
<pre><code>## [1] 599.9315</code></pre>
<p>The degrees of freedom for the munerator sum of squares are the number of free parameters in the model. This is one less than the number of groups because we need to calculate the grand mean from the data, and thus use up degree of freedom. In order to calculate the residuals we need to calculate three means in this case, so the denominator degree of freedom is the total sample size minus three.</p>
</div>
<div id="regression-1" class="section level3">
<h3><span class="header-section-number">11.4.1</span> Regression</h3>
<p>The set up for regression is in effect identical, apart from the fact that the fitted values are continuous rather than group means. So if we invent some data</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x&lt;-<span class="dv">11</span><span class="op">:</span><span class="dv">40</span>
y&lt;-<span class="dv">10</span><span class="op">+</span>x<span class="op">*</span><span class="dv">2</span><span class="op">+</span><span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dv">0</span>,<span class="dv">10</span>)
<span class="kw">plot</span>(y<span class="op">~</span>x)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-174-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x)
d&lt;-<span class="kw">data.frame</span>(x,y,<span class="dt">fitted=</span><span class="kw">fitted</span>(mod),<span class="dt">residuals=</span><span class="kw">residuals</span>(mod))
<span class="kw">head</span>(d)</code></pre></div>
<pre><code>##    x        y   fitted  residuals
## 1 11 45.58680 32.84861  12.738183
## 2 12 32.97212 34.88166  -1.909533
## 3 13 39.87672 36.91470   2.962016
## 4 14 37.46195 38.94774  -1.485794
## 5 15 26.22940 40.98079 -14.751383
## 6 16 37.85005 43.01383  -5.163776</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(y<span class="op">~</span>x)
<span class="kw">points</span>(x,<span class="kw">fitted</span>(mod),<span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">bg=</span><span class="dv">2</span>)
<span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">mean</span>(y),<span class="dt">lwd=</span><span class="dv">4</span>,<span class="dt">col=</span><span class="dv">3</span>)

<span class="kw">arrows</span>(x,<span class="kw">fitted</span>(mod),x,<span class="kw">mean</span>(y),<span class="dt">code=</span><span class="dv">3</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nsqrs&lt;-(d<span class="op">$</span>fitted<span class="op">-</span><span class="kw">mean</span>(y))<span class="op">^</span><span class="dv">2</span>
nsumsqrs&lt;-<span class="kw">sum</span>(nsqrs)</code></pre></div>
</div>
<div id="residuals" class="section level3">
<h3><span class="header-section-number">11.4.2</span> Residuals</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(y<span class="op">~</span>x)
<span class="kw">points</span>(x,<span class="kw">fitted</span>(mod),<span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">bg=</span><span class="dv">2</span>)
<span class="kw">arrows</span>(x,<span class="kw">fitted</span>(mod),x,y,<span class="dt">code=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="Quantitative_and_Spatial_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dsqrs&lt;-d<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>
dsumsqrs&lt;-<span class="kw">sum</span>(dsqrs)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod&lt;-<span class="kw">lm</span>(y<span class="op">~</span>x)
<span class="kw">anova</span>(mod)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: y
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## x          1 9289.5  9289.5  141.99 1.759e-12 ***
## Residuals 28 1831.9    65.4                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nsumsqrs</code></pre></div>
<pre><code>## [1] 9289.517</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dsumsqrs</code></pre></div>
<pre><code>## [1] 1831.902</code></pre>
</div>
</div>
<div id="where-does-r-squared-coefficient-of-determination-come-from" class="section level2">
<h2><span class="header-section-number">11.5</span> Where does R squared (coefficient of determination) come from?</h2>
<p>The “explained variability” in the data is often reported using R squared. High values suggest that a large proportion of the variability is “explained” by the model, whether the model is a regression or an ANOVA. Where does that fit in? Well the total sum of squares is the sum of all the squared distances that we have calculated. If we divide the sum of squares attributable to the model by the total we get the proportion of the variability attributable to the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">totsumsqrs&lt;-nsumsqrs<span class="op">+</span>dsumsqrs
nsumsqrs<span class="op">/</span>totsumsqrs</code></pre></div>
<pre><code>## [1] 0.8352817</code></pre>
<p>We can see that this is the same as R provides by asking for a summary.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mod)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.751  -5.120  -1.579   5.365  18.129 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  10.4851     4.5945   2.282   0.0303 *  
## x             2.0330     0.1706  11.916 1.76e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.089 on 28 degrees of freedom
## Multiple R-squared:  0.8353, Adjusted R-squared:  0.8294 
## F-statistic:   142 on 1 and 28 DF,  p-value: 1.759e-12</code></pre>
<div id="violations-of-assumptions" class="section level3">
<h3><span class="header-section-number">11.5.1</span> Violations of assumptions</h3>
<p>What do you do if your diagnostic analysis shows that there is a problem with the model? The first thing to realise is that all models are approximations of reality. As the statistician G.E. Box famously stated “All models are wrong … but some are useful.” If journal editors and referees only admitted papers which used the “correct” model ecological publishing would stop in its tracks. The important point to be aware of is that not all violations of the assumptions are equally serious. Almost all of them can be handled by more advanced modelling, but sometimes it is simply enough to point out that a minor violation was noticed, but it was not considered serious enough to prevent further analysis, together with a clearly stated justification.</p>
<div id="normality-of-the-residuals" class="section level4">
<h4><span class="header-section-number">11.5.1.1</span> Normality of the residuals</h4>
<p>This is considered to be the least important assumption of the model. Slight deviations from normality will not usually affect the conclusions drawn. Furthermore some influential authors, eg Sokal and Rolf, state that the central limit theorem means that the assumption can safely be ignored for large (n&gt;30) samples. However, be careful with this, as the assumption is that the residuals are non-normal, but homogeneous. This is unlikely to occcur.</p>
</div>
<div id="fixed-values-of-the-independent-variable" class="section level4">
<h4><span class="header-section-number">11.5.1.2</span> Fixed values of the independent variable</h4>
<p>This assumption is in fact nearly always violated in ecological studies. We never measure anything without error. The main point to be aware of is that it is error relative to the range that causes an issue. So, if we measure a variable such as tree height with an accuracy of 10cm and the range of values falls between 5m and 20m there is no problem. However if the range of heights were to be only between 10m and 11m an issue may arise. You should always aim to have a large range of values for the explanatory variable with respect to measurement errors.</p>
</div>
<div id="homogeneity-of-variance-2" class="section level4">
<h4><span class="header-section-number">11.5.1.3</span> Homogeneity of variance</h4>
<p>Violations of this assumption can be quite serious. However you should be aware that fixing the problem using techniques such as weighted regression will not affect the slope of the regression line. It will affect the p-values (making them larger) and confidence intervals (making them wider). If the p-value from the uncorrected model is very small (p&lt;0.001) then a correction for heterogeneity of variance is unlikely to result in a loss of significance. If the p-value is close to the conventional cut off (p&lt;0.05) then the correction will almost certainly change your conclusions. In some cases the apparent heterogenity is the result of outliers that need removal. Doing this will of course change the slope.</p>
</div>
<div id="incorrect-model-form" class="section level4">
<h4><span class="header-section-number">11.5.1.4</span> Incorrect model form</h4>
<p>A regression is a straight line. In many ecological situations the true responses take the form of a curve of some kind. Asymptotes are very commonly predicted both from theory and “common sense”. For example, adding more nitrogen fertilizer beyond a certain point will not produce any more growth. The biggest problem for regression in these circumstances is not that the model does not fit. It may approximate quite well to one part of the curve. The issue is that the functional form is misleading and does not represent the underlying process.</p>
</div>
<div id="influential-outliers" class="section level4">
<h4><span class="header-section-number">11.5.1.5</span> Influential outliers</h4>
<p>We have seen that an outlier does not necessarily influence the regression unless it also has high leverage. You have to think carefully before simply removing these points. If points at the extreme ends of the x axis have high residual values it may be that the model is badly formed. We have seen the potential for this in the example above. In this case you may want to restrict a linear regression to the linear part of the relationship and remove data at the ends. Flexible models such as GAMs which we will see later can deal with the issue. You may also use a data transformation to pull the extreme values in. It may well turn out that the issue simply is due to mistaken measurements, in which case the extreme values are rejected after checking. There are also other methods to formally handle the problem such as robust regression.</p>
</div>
<div id="independence-of-the-errors" class="section level4">
<h4><span class="header-section-number">11.5.1.6</span> Independence of the errors</h4>
<p>This is the big issue. Violations of this assumption are always serious. The main problem is that if observations are not independent the model is claiming many more degrees of freedom (replication) than is justified. This means that the model cannot be generalised. The issue affects many, if not all, ecological studies to some extent. Measurements are rarely truly independent from each other in space and time. The issue affects the interpetation of the p-value and confidence intervals of the model. While the model may still be suitable for prediction within its sample space it will not generalise beyond it. In the next class we will look at an example in detail that may help to clarify this.</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-one-way-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="advice-on-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["Quantitative_and_Spatial.pdf", "Quantitative_and_Spatial.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
